= Abridge VSCode Extension

== Prerequisites

* Abridge command line program built
* VSCode
* yarn (or npm)
* A sacrificial / backed-up Clojure project directory

== Building

* In some terminal:

----
# install dependencies
yarn
# build + watch for changes
yarn shadow-cljs watch dev
----

If all went well, there should now be a fresh file at lib/main.js (the "compiled" extension).

* In the bin subdirectory, make a copy of the abridge binary, or create a symlink to it.

== Starting

* Start VSCode

* Open the folder containing this file in VSCode.

* From the menu bar, choose Debug -> Start Debugging (or press F5).  This should result in another VSCode window opening.

* In the new VSCode window, open a folder that has at least one Clojure file in it.

== Invoking

* Open a Clojure file in an editor pane.

* Bring up the https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette[command palette], look for / start typing "Fold All", and once found / selected, press Enter / Return.

* This should result in multi-line strings being folded.

Note that this extension provides the computation of the folding ranges; the folding functionality is just leveraging VSCode's built-in commands.
