(function(root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.returnExports = factory();
  }
})(this, function() {
  var shadow$umd$export = null;

  var f;
function w(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),da=0;function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function za(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function Ba(a,b){null!=a&&this.append.apply(this,arguments)}f=Ba.prototype;f.La="";f.set=function(a){this.La=""+a};f.append=function(a,b,c){this.La+=String(a);if(null!=b)for(var d=1;d<arguments.length;d++)this.La+=arguments[d];return this};f.clear=function(){this.La=""};f.toString=function(){return this.La};var Da={},Ea={},p,D={},Ga=null,Ja=!0,Ka=null;function Ma(){return new Na(null,5,[Oa,!0,Pa,!0,Qa,!1,Ra,!1,Sa,null],null)}function Ta(){Ja=!1;Ga=function(){return console.log.apply(console,Aa(arguments))}}function E(a){return null!=a&&!1!==a}function F(a,b){return a[w(null==b?null:b)]?!0:a._?!0:!1}function I(a,b){var c=null==b?null:b.constructor;c=E(E(c)?c.ub:c)?c.gb:w(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function Ua(a){var b=a.gb;return E(b)?b:K.a(a)}
var Wa="undefined"!==typeof Symbol&&"function"===w(Symbol)?Symbol.iterator:"@@iterator";function Xa(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function Ya(a){function b(d,e){d.push(e);return d}var c=[];return Za?Za(b,c,a):$a.call(null,b,c,a)}function ab(){}
var bb=function bb(a){if(null!=a&&null!=a.da)return a.da(a);var c=bb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=bb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("ICounted.-count",a);};function cb(){}var db=function db(a){if(null!=a&&null!=a.X)return a.X(a);var c=db[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=db._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IEmptyableCollection.-empty",a);};function eb(){}
var fb=function fb(a,b){if(null!=a&&null!=a.U)return a.U(a,b);var d=fb[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=fb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("ICollection.-conj",a);};function gb(){}var hb=function hb(a){switch(arguments.length){case 2:return hb.b(arguments[0],arguments[1]);case 3:return hb.g(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};
hb.b=function(a,b){if(null!=a&&null!=a.T)return a.T(a,b);var c=hb[w(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=hb._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw I("IIndexed.-nth",a);};hb.g=function(a,b,c){if(null!=a&&null!=a.$)return a.$(a,b,c);var d=hb[w(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=hb._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw I("IIndexed.-nth",a);};hb.P=3;function ib(){}
var O=function O(a){if(null!=a&&null!=a.ea)return a.ea(a);var c=O[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=O._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("ISeq.-first",a);},jb=function jb(a){if(null!=a&&null!=a.ha)return a.ha(a);var c=jb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=jb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("ISeq.-rest",a);};function kb(){}function mb(){}
var nb=function nb(a){switch(arguments.length){case 2:return nb.b(arguments[0],arguments[1]);case 3:return nb.g(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};nb.b=function(a,b){if(null!=a&&null!=a.K)return a.K(a,b);var c=nb[w(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=nb._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw I("ILookup.-lookup",a);};
nb.g=function(a,b,c){if(null!=a&&null!=a.v)return a.v(a,b,c);var d=nb[w(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=nb._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw I("ILookup.-lookup",a);};nb.P=3;var ob=function ob(a,b,c){if(null!=a&&null!=a.Ma)return a.Ma(a,b,c);var e=ob[w(null==a?null:a)];if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);e=ob._;if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);throw I("IAssociative.-assoc",a);};function pb(){}
var qb=function qb(a){if(null!=a&&null!=a.Fb)return a.key;var c=qb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=qb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IMapEntry.-key",a);},rb=function rb(a){if(null!=a&&null!=a.Gb)return a.F;var c=rb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=rb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IMapEntry.-val",a);};function sb(){}
var tb=function tb(a){if(null!=a&&null!=a.xb)return a.F;var c=tb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=tb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IDeref.-deref",a);};function ub(){}
var vb=function vb(a){if(null!=a&&null!=a.M)return a.M(a);var c=vb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=vb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IMeta.-meta",a);},wb=function wb(a,b){if(null!=a&&null!=a.O)return a.O(a,b);var d=wb[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=wb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("IWithMeta.-with-meta",a);};function yb(){}
var zb=function zb(a){switch(arguments.length){case 2:return zb.b(arguments[0],arguments[1]);case 3:return zb.g(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};zb.b=function(a,b){if(null!=a&&null!=a.ba)return a.ba(a,b);var c=zb[w(null==a?null:a)];if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);c=zb._;if(null!=c)return c.b?c.b(a,b):c.call(null,a,b);throw I("IReduce.-reduce",a);};
zb.g=function(a,b,c){if(null!=a&&null!=a.ca)return a.ca(a,b,c);var d=zb[w(null==a?null:a)];if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);d=zb._;if(null!=d)return d.g?d.g(a,b,c):d.call(null,a,b,c);throw I("IReduce.-reduce",a);};zb.P=3;function Ab(){}
var Bb=function Bb(a,b,c){if(null!=a&&null!=a.eb)return a.eb(a,b,c);var e=Bb[w(null==a?null:a)];if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);e=Bb._;if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);throw I("IKVReduce.-kv-reduce",a);},Cb=function Cb(a,b){if(null!=a&&null!=a.G)return a.G(a,b);var d=Cb[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Cb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("IEquiv.-equiv",a);},Db=function Db(a){if(null!=a&&null!=a.S)return a.S(a);
var c=Db[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Db._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IHash.-hash",a);};function Eb(){}var Fb=function Fb(a){if(null!=a&&null!=a.H)return a.H(a);var c=Fb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Fb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("ISeqable.-seq",a);};function Gb(){}function Hb(){}function Ib(){}
var Jb=function Jb(a,b){if(null!=a&&null!=a.sb)return a.sb(a,b);var d=Jb[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Jb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("IWriter.-write",a);};function Kb(){}
var Lb=function Lb(a,b,c){if(null!=a&&null!=a.N)return a.N(a,b,c);var e=Lb[w(null==a?null:a)];if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);e=Lb._;if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);throw I("IPrintWithWriter.-pr-writer",a);},Mb=function Mb(a){if(null!=a&&null!=a.Va)return a.Va(a);var c=Mb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Mb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IEditableCollection.-as-transient",a);},Nb=function Nb(a,b){if(null!=
a&&null!=a.Xa)return a.Xa(a,b);var d=Nb[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Nb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("ITransientCollection.-conj!",a);},Ob=function Ob(a){if(null!=a&&null!=a.fb)return a.fb(a);var c=Ob[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Ob._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("ITransientCollection.-persistent!",a);},Pb=function Pb(a,b,c){if(null!=a&&null!=a.Ta)return a.Ta(a,b,c);var e=
Pb[w(null==a?null:a)];if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);e=Pb._;if(null!=e)return e.g?e.g(a,b,c):e.call(null,a,b,c);throw I("ITransientAssociative.-assoc!",a);},Qb=function Qb(a){if(null!=a&&null!=a.mb)return a.mb(a);var c=Qb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Qb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IChunk.-drop-first",a);},Rb=function Rb(a){if(null!=a&&null!=a.jb)return a.jb(a);var c=Rb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):
c.call(null,a);c=Rb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IChunkedSeq.-chunked-first",a);},Sb=function Sb(a){if(null!=a&&null!=a.bb)return a.bb(a);var c=Sb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Sb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IChunkedSeq.-chunked-rest",a);};function Vb(){}
var Wb=function Wb(a){if(null!=a&&null!=a.qa)return a.qa(a);var c=Wb[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Wb._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IIterable.-iterator",a);};function Xb(a){this.Nb=a;this.h=1073741824;this.o=0}Xb.prototype.sb=function(a,b){return this.Nb.append(b)};function Yb(a){var b=new Ba;a.N(null,new Xb(b),Ma());return K.a(b)}
var Zb="undefined"!==typeof Math&&"undefined"!==typeof Math.imul&&0!==Math.imul(4294967295,5)?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function $b(a){a=Zb(a|0,-862048943);return Zb(a<<15|a>>>-15,461845907)}function ac(a,b){a=(a|0)^(b|0);return Zb(a<<13|a>>>-13,5)+-430675100|0}function bc(a,b){a=(a|0)^b;a=Zb(a^a>>>16,-2048144789);a=Zb(a^a>>>13,-1028477387);return a^a>>>16}
function cc(a){a:{var b=1;for(var c=0;;)if(b<a.length)c=ac(c,$b(a.charCodeAt(b-1)|a.charCodeAt(b)<<16)),b+=2;else{b=c;break a}}return bc(1===(a.length&1)?b^$b(a.charCodeAt(a.length-1)):b,Zb(2,a.length))}var dc={},ec=0;function fc(a){255<ec&&(dc={},ec=0);if(null==a)return 0;var b=dc[a];if("number"===typeof b)a=b;else{a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)d=Zb(31,d)+a.charCodeAt(c),c+=1;else{b=d;break a}else b=0;else b=0;dc[a]=b;ec+=1;a=b}return a}
function gc(a){if(null!=a&&(a.h&4194304||D===a.Sb))return a.S(null)^0;if("number"===typeof a){if(E(isFinite(a)))return Math.floor(a)%2147483647;switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return!0===a?a=1231:!1===a?a=1237:"string"===typeof a?(a=fc(a),a=0===a?a:bc(ac(0,$b(a)),4)):a=a instanceof Date?a.valueOf()^0:null==a?0:Db(a)^0,a}function hc(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function ic(a,b,c,d,e){this.Ra=a;this.name=b;this.Ka=c;this.Sa=d;this.pa=e;this.h=2154168321;this.o=4096}f=ic.prototype;f.toString=function(){return this.Ka};f.G=function(a,b){return b instanceof ic?this.Ka===b.Ka:!1};f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};
f.a=function(a){return jc.b?jc.b(a,this):jc.call(null,a,this)};f.b=function(a,b){return jc.g?jc.g(a,this,b):jc.call(null,a,this,b)};f.M=function(){return this.pa};f.O=function(a,b){return new ic(this.Ra,this.name,this.Ka,this.Sa,b)};f.S=function(){var a=this.Sa;return null!=a?a:this.Sa=a=hc(cc(this.name),fc(this.Ra))};f.N=function(a,b){return Jb(b,this.Ka)};
var v=function v(a){switch(arguments.length){case 1:return v.a(arguments[0]);case 2:return v.b(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};v.a=function(a){for(;;){if(a instanceof ic)return a;if("string"===typeof a){var b=a.indexOf("/");return 1>b?v.b(null,a):v.b(a.substring(0,b),a.substring(b+1,a.length))}if(a instanceof qd)a=a.Ja;else throw Error("no conversion to symbol");}};
v.b=function(a,b){var c=null!=a?[K.a(a),"/",K.a(b)].join(""):b;return new ic(a,b,c,null,null)};v.P=2;function kc(a){return null!=a?a.o&131072||D===a.Tb?!0:a.o?!1:F(Vb,a):F(Vb,a)}function Q(a){if(null==a)return null;if(null!=a&&(a.h&8388608||D===a.Kb))return a.H(null);if(Array.isArray(a)||"string"===typeof a)return 0===a.length?null:new lc(a,0,null);if(F(Eb,a))return Fb(a);throw Error([K.a(a)," is not ISeqable"].join(""));}
function S(a){if(null==a)return null;if(null!=a&&(a.h&64||D===a.Na))return a.ea(null);a=Q(a);return null==a?null:O(a)}function mc(a){return null!=a?null!=a&&(a.h&64||D===a.Na)?a.ha(null):(a=Q(a))?a.ha(null):nc:nc}function T(a){return null==a?null:null!=a&&(a.h&128||D===a.Wa)?a.W():Q(mc(a))}
var oc=function oc(a){switch(arguments.length){case 1:return oc.a(arguments[0]);case 2:return oc.b(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return oc.w(arguments[0],arguments[1],new lc(c.slice(2),0,null))}};oc.a=function(){return!0};oc.b=function(a,b){return null==a?null==b:a===b||Cb(a,b)};oc.w=function(a,b,c){for(;;)if(oc.b(a,b))if(T(c))a=b,b=S(c),c=T(c);else return oc.b(b,S(c));else return!1};
oc.I=function(a){var b=S(a),c=T(a);a=S(c);c=T(c);return this.w(b,a,c)};oc.P=2;function pc(a){this.u=a}pc.prototype.next=function(){if(null!=this.u){var a=S(this.u);this.u=T(this.u);return{value:a,done:!1}}return{value:null,done:!0}};function qc(a){return new pc(Q(a))}function rc(a){var b=0,c=1;for(a=Q(a);;)if(null!=a)b+=1,c=Zb(31,c)+gc(S(a))|0,a=T(a);else return bc(ac(0,$b(c)),b)}var sc=bc(ac(0,$b(1)),0);
function tc(a){var b=0,c=0;for(a=Q(a);;)if(null!=a)b+=1,c=c+gc(S(a))|0,a=T(a);else return bc(ac(0,$b(c)),b)}var uc=bc(ac(0,$b(0)),0);ab["null"]=!0;bb["null"]=function(){return 0};Date.prototype.G=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Cb.number=function(a,b){return a===b};ub["function"]=!0;vb["function"]=function(){return null};Db._=function(a){return a[aa]||(a[aa]=++da)};function vc(){this.F=!1;this.h=32768;this.o=0}vc.prototype.xb=function(){return this.F};
function wc(a){return a instanceof vc}function xc(a){return tb(a)}function yc(a,b){var c=a.length;if(0===a.length)return b.B?b.B():b.call(null);for(var d=a[0],e=1;;)if(e<c){var g=a[e];d=b.b?b.b(d,g):b.call(null,d,g);if(wc(d))return tb(d);e+=1}else return d}function zc(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c];e=b.b?b.b(e,g):b.call(null,e,g);if(wc(e))return tb(e);c+=1}else return e}
function Ac(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.b?b.b(c,g):b.call(null,c,g);if(wc(c))return tb(c);d+=1}else return c}function Bc(a){return null!=a?a.h&2||D===a.wb?!0:a.h?!1:F(ab,a):F(ab,a)}function Cc(a){return null!=a?a.h&16||D===a.ob?!0:a.h?!1:F(gb,a):F(gb,a)}function V(a,b,c){var d=X.a?X.a(a):X.call(null,a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(oc.b(Dc?Dc(a,c):Ec.call(null,a,c),b))return c;c+=1}else return-1}
function Z(a,b,c){var d=X.a?X.a(a):X.call(null,a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if(oc.b(Dc?Dc(a,c):Ec.call(null,a,c),b))return c;--c}else return-1}function Fc(a,b){this.c=a;this.j=b}Fc.prototype.fa=function(){return this.j<this.c.length};Fc.prototype.next=function(){var a=this.c[this.j];this.j+=1;return a};function lc(a,b,c){this.c=a;this.j=b;this.l=c;this.h=166592766;this.o=139264}f=lc.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X.a?X.a(this):X.call(null,this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.T=function(a,b){a=b+this.j;if(0<=a&&a<this.c.length)return this.c[a];throw Error("Index out of bounds");};f.$=function(a,b,c){a=b+this.j;return 0<=a&&a<this.c.length?this.c[a]:c};
f.qa=function(){return new Fc(this.c,this.j)};f.M=function(){return this.l};f.W=function(){return this.j+1<this.c.length?new lc(this.c,this.j+1,null):null};f.da=function(){var a=this.c.length-this.j;return 0>a?0:a};f.S=function(){return rc(this)};f.G=function(a,b){return Gc.b?Gc.b(this,b):Gc.call(null,this,b)};f.X=function(){return nc};f.ba=function(a,b){return Ac(this.c,b,this.c[this.j],this.j+1)};f.ca=function(a,b,c){return Ac(this.c,b,c,this.j)};f.ea=function(){return this.c[this.j]};
f.ha=function(){return this.j+1<this.c.length?new lc(this.c,this.j+1,null):nc};f.H=function(){return this.j<this.c.length?this:null};f.O=function(a,b){return b===this.l?this:new lc(this.c,this.j,b)};f.U=function(a,b){return Hc.b?Hc.b(b,this):Hc.call(null,b,this)};lc.prototype[Wa]=function(){return qc(this)};function Ic(a){return 0<a.length?new lc(a,0,null):null}Cb._=function(a,b){return a===b};
var Jc=function Jc(a){switch(arguments.length){case 0:return Jc.B();case 1:return Jc.a(arguments[0]);case 2:return Jc.b(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Jc.w(arguments[0],arguments[1],new lc(c.slice(2),0,null))}};Jc.B=function(){return Kc};Jc.a=function(a){return a};Jc.b=function(a,b){return null!=a?fb(a,b):new Lc(null,b,null,1,null)};
Jc.w=function(a,b,c){for(;;)if(E(c))a=Jc.b(a,b),b=S(c),c=T(c);else return Jc.b(a,b)};Jc.I=function(a){var b=S(a),c=T(a);a=S(c);c=T(c);return this.w(b,a,c)};Jc.P=2;function Mc(a){return null==a?null:null!=a&&(a.h&4||D===a.zb)?a.X(null):(null!=a?a.h&4||D===a.zb||(a.h?0:F(cb,a)):F(cb,a))?db(a):null}
function X(a){if(null!=a)if(null!=a&&(a.h&2||D===a.wb))a=a.da(null);else if(Array.isArray(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.h&8388608||D===a.Kb))a:{a=Q(a);for(var b=0;;){if(Bc(a)){a=b+bb(a);break a}a=T(a);b+=1}}else a=bb(a);else a=0;return a}function Nc(a,b,c){for(;;){if(null==a)return c;if(0===b)return Q(a)?S(a):c;if(Cc(a))return hb(a,b,c);if(Q(a))a=T(a),--b;else return c}}
function Ec(a){switch(arguments.length){case 2:return Dc(arguments[0],arguments[1]);case 3:return Oc(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}
function Dc(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.h&16||D===a.ob))return a.T(null,b);if(Array.isArray(a)){if(-1<b&&b<a.length)return a[b|0];throw Error("Index out of bounds");}if("string"===typeof a){if(-1<b&&b<a.length)return a.charAt(b|0);throw Error("Index out of bounds");}if(null!=a&&(a.h&64||D===a.Na)||null!=a&&(a.h&16777216||D===a.rb)){if(0>b)throw Error("Index out of bounds");a:for(;;){if(null==a)throw Error("Index out of bounds");
if(0===b){if(Q(a)){a=S(a);break a}throw Error("Index out of bounds");}if(Cc(a)){a=hb(a,b);break a}if(Q(a))a=T(a),--b;else throw Error("Index out of bounds");}return a}if(F(gb,a))return hb(a,b);throw Error(["nth not supported on this type ",K.a(Ua(null==a?null:a.constructor))].join(""));}
function Oc(a,b,c){if("number"!==typeof b)throw Error("Index argument to nth must be a number.");if(null==a)return c;if(null!=a&&(a.h&16||D===a.ob))return a.$(null,b,c);if(Array.isArray(a))return-1<b&&b<a.length?a[b|0]:c;if("string"===typeof a)return-1<b&&b<a.length?a.charAt(b|0):c;if(null!=a&&(a.h&64||D===a.Na)||null!=a&&(a.h&16777216||D===a.rb))return 0>b?c:Nc(a,b,c);if(F(gb,a))return hb(a,b,c);throw Error(["nth not supported on this type ",K.a(Ua(null==a?null:a.constructor))].join(""));}
var jc=function jc(a){switch(arguments.length){case 2:return jc.b(arguments[0],arguments[1]);case 3:return jc.g(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};jc.b=function(a,b){return null==a?null:null!=a&&(a.h&256||D===a.Eb)?a.K(null,b):Array.isArray(a)?null!=b&&b<a.length?a[b|0]:null:"string"===typeof a?null!=b&&b<a.length?a.charAt(b|0):null:F(mb,a)?nb(a,b):null};
jc.g=function(a,b,c){return null!=a?null!=a&&(a.h&256||D===a.Eb)?a.v(null,b,c):Array.isArray(a)?null!=b&&-1<b&&b<a.length?a[b|0]:c:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):c:F(mb,a)?nb(a,b,c):c:c};jc.P=3;var Pc=function Pc(a){switch(arguments.length){case 3:return Pc.g(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Pc.w(arguments[0],arguments[1],arguments[2],new lc(c.slice(3),0,null))}};
Pc.g=function(a,b,c){return null!=a&&(a.h&512||D===a.D)?a.Ma(null,b,c):null!=a?ob(a,b,c):Qc([b,c])};Pc.w=function(a,b,c,d){for(;;)if(a=Pc.g(a,b,c),E(d))b=S(d),c=S(T(d)),d=T(T(d));else return a};Pc.I=function(a){var b=S(a),c=T(a);a=S(c);var d=T(c);c=S(d);d=T(d);return this.w(b,a,c,d)};Pc.P=3;function Rc(a,b){this.f=a;this.l=b;this.h=393217;this.o=0}f=Rc.prototype;f.M=function(){return this.l};f.O=function(a,b){return new Rc(this.f,b)};
f.call=function(a){switch(arguments.length-1){case 0:return this.B();case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);case 3:return this.g(arguments[1],arguments[2],arguments[3]);case 4:return this.V(arguments[1],arguments[2],arguments[3],arguments[4]);case 5:return this.ja(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 6:return this.Da(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);case 7:return this.Ea(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7]);case 8:return this.Fa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8]);case 9:return this.Ga(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9]);case 10:return this.sa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10]);
case 11:return this.ta(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11]);case 12:return this.ua(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12]);case 13:return this.va(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],
arguments[11],arguments[12],arguments[13]);case 14:return this.wa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14]);case 15:return this.xa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15]);case 16:return this.ya(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16]);case 17:return this.za(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17]);case 18:return this.Aa(arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18]);case 19:return this.Ba(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19]);case 20:return this.Ca(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19],arguments[20]);case 21:var b=arguments[1],c=arguments[2],d=arguments[3],e=arguments[4],g=arguments[5],h=arguments[6],k=arguments[7],l=arguments[8],m=arguments[9],q=arguments[10],n=arguments[11],r=arguments[12],t=arguments[13],u=arguments[14],z=arguments[15],
B=arguments[16],N=arguments[17],W=arguments[18],ca=arguments[19],sa=arguments[20],Ha=arguments[21];return Sc.cb?Sc.cb(this.f,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa,Ha):Sc.call(null,this.f,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa,Ha);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.B=function(){return this.f.B?this.f.B():this.f.call(null)};
f.a=function(a){return this.f.a?this.f.a(a):this.f.call(null,a)};f.b=function(a,b){return this.f.b?this.f.b(a,b):this.f.call(null,a,b)};f.g=function(a,b,c){return this.f.g?this.f.g(a,b,c):this.f.call(null,a,b,c)};f.V=function(a,b,c,d){return this.f.V?this.f.V(a,b,c,d):this.f.call(null,a,b,c,d)};f.ja=function(a,b,c,d,e){return this.f.ja?this.f.ja(a,b,c,d,e):this.f.call(null,a,b,c,d,e)};f.Da=function(a,b,c,d,e,g){return this.f.Da?this.f.Da(a,b,c,d,e,g):this.f.call(null,a,b,c,d,e,g)};
f.Ea=function(a,b,c,d,e,g,h){return this.f.Ea?this.f.Ea(a,b,c,d,e,g,h):this.f.call(null,a,b,c,d,e,g,h)};f.Fa=function(a,b,c,d,e,g,h,k){return this.f.Fa?this.f.Fa(a,b,c,d,e,g,h,k):this.f.call(null,a,b,c,d,e,g,h,k)};f.Ga=function(a,b,c,d,e,g,h,k,l){return this.f.Ga?this.f.Ga(a,b,c,d,e,g,h,k,l):this.f.call(null,a,b,c,d,e,g,h,k,l)};f.sa=function(a,b,c,d,e,g,h,k,l,m){return this.f.sa?this.f.sa(a,b,c,d,e,g,h,k,l,m):this.f.call(null,a,b,c,d,e,g,h,k,l,m)};
f.ta=function(a,b,c,d,e,g,h,k,l,m,q){return this.f.ta?this.f.ta(a,b,c,d,e,g,h,k,l,m,q):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q)};f.ua=function(a,b,c,d,e,g,h,k,l,m,q,n){return this.f.ua?this.f.ua(a,b,c,d,e,g,h,k,l,m,q,n):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n)};f.va=function(a,b,c,d,e,g,h,k,l,m,q,n,r){return this.f.va?this.f.va(a,b,c,d,e,g,h,k,l,m,q,n,r):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r)};
f.wa=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t){return this.f.wa?this.f.wa(a,b,c,d,e,g,h,k,l,m,q,n,r,t):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t)};f.xa=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u){return this.f.xa?this.f.xa(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u)};f.ya=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z){return this.f.ya?this.f.ya(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z)};
f.za=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B){return this.f.za?this.f.za(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B)};f.Aa=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N){return this.f.Aa?this.f.Aa(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N)};
f.Ba=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W){return this.f.Ba?this.f.Ba(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W)};f.Ca=function(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca){return this.f.Ca?this.f.Ca(a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca):this.f.call(null,a,b,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca)};function Tc(a,b){return"function"==w(a)?new Rc(a,b):null==a?null:wb(a,b)}
function Uc(a){return null!=a&&(null!=a?a.h&131072||D===a.Hb||(a.h?0:F(ub,a)):F(ub,a))?vb(a):null}function Vc(a){return null==a?!1:null!=a?a.h&8||D===a.Qb?!0:a.h?!1:F(eb,a):F(eb,a)}function Wc(a){return null!=a?a.h&16777216||D===a.rb?!0:a.h?!1:F(Gb,a):F(Gb,a)}function Xc(a){return null==a?!1:null!=a?a.h&1024||D===a.Wb?!0:a.h?!1:F(pb,a):F(pb,a)}function Zc(a){return null!=a?a.h&67108864||D===a.Yb?!0:a.h?!1:F(Ib,a):F(Ib,a)}
function $c(a){return null!=a?a.h&16384||D===a.Zb?!0:a.h?!1:F(sb,a):F(sb,a)}function ad(a){return null!=a?a.o&512||D===a.Pb?!0:!1:!1}function bd(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var cd={};function dd(a){return null==a?!1:null!=a?a.h&64||D===a.Na?!0:a.h?!1:F(ib,a):F(ib,a)}function ed(a){return null==a?!1:!1===a?!1:!0}function fd(a,b){var c=Q(b);return c?(b=S(c),c=T(c),Za?Za(a,b,c):$a.call(null,a,b,c)):a.B?a.B():a.call(null)}
function gd(a,b,c){for(c=Q(c);;)if(c){var d=S(c);b=a.b?a.b(b,d):a.call(null,b,d);if(wc(b))return tb(b);c=T(c)}else return b}function hd(a,b){a=Wb(a);if(E(a.fa()))for(var c=a.next();;)if(a.fa()){var d=a.next();c=b.b?b.b(c,d):b.call(null,c,d);if(wc(c))return tb(c)}else return c;else return b.B?b.B():b.call(null)}function id(a,b,c){for(a=Wb(a);;)if(a.fa()){var d=a.next();c=b.b?b.b(c,d):b.call(null,c,d);if(wc(c))return tb(c)}else return c}
function $a(a){switch(arguments.length){case 2:var b=arguments[0],c=arguments[1];return null!=c&&(c.h&524288||D===c.Jb)?c.ba(null,b):Array.isArray(c)?yc(c,b):"string"===typeof c?yc(c,b):F(yb,c)?zb(c,b):kc(c)?hd(c,b):fd(b,c);case 3:return Za(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}
function Za(a,b,c){return null!=c&&(c.h&524288||D===c.Jb)?c.ca(null,a,b):Array.isArray(c)?zc(c,a,b):"string"===typeof c?zc(c,a,b):F(yb,c)?zb(c,a,b):kc(c)?id(c,a,b):gd(a,b,c)}function jd(a,b){return null!=b?Bb(b,a,!0):!0}function kd(a){return a}function ld(a,b,c,d){a=a.a?a.a(b):a.call(null,b);c=Za(a,c,d);return a.a?a.a(c):a.call(null,c)}function md(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}
function nd(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}var K=function K(a){switch(arguments.length){case 0:return K.B();case 1:return K.a(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return K.w(arguments[0],new lc(c.slice(1),0,null))}};K.B=function(){return""};K.a=function(a){return null==a?"":[a].join("")};K.w=function(a,b){for(a=new Ba(K.a(a));;)if(E(b))a=a.append(K.a(S(b))),b=T(b);else return a.toString()};
K.I=function(a){var b=S(a);a=T(a);return this.w(b,a)};K.P=1;function Gc(a,b){if(Wc(b))if(Bc(a)&&Bc(b)&&X(a)!==X(b))a=!1;else a:for(a=Q(a),b=Q(b);;){if(null==a){a=null==b;break a}if(null!=b&&oc.b(S(a),S(b)))a=T(a),b=T(b);else{a=!1;break a}}else a=null;return ed(a)}function Lc(a,b,c,d,e){this.l=a;this.first=b;this.Ha=c;this.count=d;this.m=e;this.h=65937646;this.o=8192}f=Lc.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,this.count)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){return 1===this.count?null:this.Ha};f.da=function(){return this.count};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};
f.X=function(){return wb(nc,this.l)};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return this.first};f.ha=function(){return 1===this.count?nc:this.Ha};f.H=function(){return this};f.O=function(a,b){return b===this.l?this:new Lc(b,this.first,this.Ha,this.count,this.m)};f.U=function(a,b){return new Lc(this.l,b,this,this.count+1,null)};Lc.prototype[Wa]=function(){return qc(this)};function od(a){this.l=a;this.h=65937614;this.o=8192}f=od.prototype;
f.toString=function(){return Yb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){return null};f.da=function(){return 0};f.S=function(){return sc};f.G=function(a,b){return(null!=b?b.h&33554432||D===b.Vb||(b.h?0:F(Hb,b)):F(Hb,b))||Wc(b)?null==Q(b):!1};f.X=function(){return this};
f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return null};f.ha=function(){return nc};f.H=function(){return null};f.O=function(a,b){return b===this.l?this:new od(b)};f.U=function(a,b){return new Lc(this.l,b,null,1,null)};var nc=new od(null);od.prototype[Wa]=function(){return qc(this)};function pd(a,b,c,d){this.l=a;this.first=b;this.Ha=c;this.m=d;this.h=65929452;this.o=8192}f=pd.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){return null==this.Ha?null:Q(this.Ha)};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};
f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return this.first};f.ha=function(){return null==this.Ha?nc:this.Ha};f.H=function(){return this};f.O=function(a,b){return b===this.l?this:new pd(b,this.first,this.Ha,this.m)};f.U=function(a,b){return new pd(null,b,this,null)};pd.prototype[Wa]=function(){return qc(this)};function Hc(a,b){return null==b?new Lc(null,a,null,1,null):null!=b&&(b.h&64||D===b.Na)?new pd(null,a,b,null):new pd(null,a,Q(b),null)}
function qd(a,b,c,d){this.Ra=a;this.name=b;this.Ja=c;this.Sa=d;this.h=2153775105;this.o=4096}f=qd.prototype;f.toString=function(){return[":",K.a(this.Ja)].join("")};f.G=function(a,b){return b instanceof qd?this.Ja===b.Ja:!1};f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};
f.a=function(a){return jc.b(a,this)};f.b=function(a,b){return jc.g(a,this,b)};f.S=function(){var a=this.Sa;return null!=a?a:this.Sa=a=hc(cc(this.name),fc(this.Ra))+2654435769|0};f.N=function(a,b){return Jb(b,[":",K.a(this.Ja)].join(""))};function x(a){if(null!=a&&(a.o&4096||D===a.Ib))return a.Ra;throw Error(["Doesn't support namespace: ",K.a(a)].join(""));}
var rd=function rd(a){switch(arguments.length){case 1:return rd.a(arguments[0]);case 2:return rd.b(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}};rd.a=function(a){if(a instanceof qd)return a;if(a instanceof ic)return new qd(x(a),sd.a?sd.a(a):sd.call(null,a),a.Ka,null);if("string"===typeof a){var b=a.split("/");return 2===b.length?new qd(b[0],b[1],a,null):new qd(null,b[0],a,null)}return null};
rd.b=function(a,b){a=a instanceof qd?sd.a?sd.a(a):sd.call(null,a):a instanceof ic?sd.a?sd.a(a):sd.call(null,a):a;b=b instanceof qd?sd.a?sd.a(b):sd.call(null,b):b instanceof ic?sd.a?sd.a(b):sd.call(null,b):b;return new qd(a,b,[E(a)?[K.a(a),"/"].join(""):null,K.a(b)].join(""),null)};rd.P=2;function td(a,b,c){this.l=a;this.Ya=b;this.u=null;this.m=c;this.h=32374988;this.o=1}f=td.prototype;f.toString=function(){return Yb(this)};
function ud(a){null!=a.Ya&&(a.u=a.Ya.B?a.Ya.B():a.Ya.call(null),a.Ya=null);return a.u}f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){this.H(null);return null==this.u?null:T(this.u)};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};f.X=function(){return wb(nc,this.l)};
f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){this.H(null);return null==this.u?null:S(this.u)};f.ha=function(){this.H(null);return null!=this.u?mc(this.u):nc};f.H=function(){ud(this);if(null==this.u)return null;for(var a=this.u;;)if(a instanceof td)a=ud(a);else return this.u=a,Q(this.u)};f.O=function(a,b){var c=this;return b===this.l?c:new td(b,function(){return c.H(null)},this.m)};f.U=function(a,b){return Hc(b,this)};td.prototype[Wa]=function(){return qc(this)};
function vd(a){this.ib=a;this.end=0;this.h=2;this.o=0}vd.prototype.add=function(a){this.ib[this.end]=a;return this.end+=1};vd.prototype.ra=function(){var a=new wd(this.ib,0,this.end);this.ib=null;return a};vd.prototype.da=function(){return this.end};function wd(a,b,c){this.c=a;this.R=b;this.end=c;this.h=524306;this.o=0}f=wd.prototype;f.da=function(){return this.end-this.R};f.T=function(a,b){return this.c[this.R+b]};f.$=function(a,b,c){return 0<=b&&b<this.end-this.R?this.c[this.R+b]:c};
f.mb=function(){if(this.R===this.end)throw Error("-drop-first of empty chunk");return new wd(this.c,this.R+1,this.end)};f.ba=function(a,b){return Ac(this.c,b,this.c[this.R],this.R+1)};f.ca=function(a,b,c){return Ac(this.c,b,c,this.R)};function xd(a,b,c,d){this.ra=a;this.ma=b;this.l=c;this.m=d;this.h=31850732;this.o=1536}f=xd.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){return 1<bb(this.ra)?new xd(Qb(this.ra),this.ma,null,null):null==this.ma?null:Fb(this.ma)};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};
f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ea=function(){return hb(this.ra,0)};f.ha=function(){return 1<bb(this.ra)?new xd(Qb(this.ra),this.ma,null,null):null==this.ma?nc:this.ma};f.H=function(){return this};f.jb=function(){return this.ra};f.bb=function(){return null==this.ma?nc:this.ma};f.O=function(a,b){return b===this.l?this:new xd(this.ra,this.ma,b,this.m)};f.U=function(a,b){return Hc(b,this)};f.nb=function(){return null==this.ma?null:this.ma};xd.prototype[Wa]=function(){return qc(this)};
function yd(a,b){return 0===bb(a)?b:new xd(a,b,null,null)}function zd(a,b){a.add(b)}function Ad(a,b){if(Bc(b))return X(b);var c=0;for(b=Q(b);;)if(null!=b&&c<a)c+=1,b=T(b);else return c}
var Bd=function Bd(a){if(null==a)return null;var c=T(a);return null==c?Q(S(a)):Hc(S(a),Bd.a?Bd.a(c):Bd.call(null,c))},Cd=function Cd(a){switch(arguments.length){case 0:return Cd.B();case 1:return Cd.a(arguments[0]);case 2:return Cd.b(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Cd.w(arguments[0],arguments[1],new lc(c.slice(2),0,null))}};Cd.B=function(){return Mb(Kc)};Cd.a=function(a){return a};
Cd.b=function(a,b){return Nb(a,b)};Cd.w=function(a,b,c){for(;;)if(a=Nb(a,b),E(c))b=S(c),c=T(c);else return a};Cd.I=function(a){var b=S(a),c=T(a);a=S(c);c=T(c);return this.w(b,a,c)};Cd.P=2;
function Dd(a,b,c){var d=Q(c);if(0===b)return a.B?a.B():a.call(null);c=O(d);var e=jb(d);if(1===b)return a.a?a.a(c):a.call(null,c);d=O(e);var g=jb(e);if(2===b)return a.b?a.b(c,d):a.call(null,c,d);e=O(g);var h=jb(g);if(3===b)return a.g?a.g(c,d,e):a.call(null,c,d,e);g=O(h);var k=jb(h);if(4===b)return a.V?a.V(c,d,e,g):a.call(null,c,d,e,g);h=O(k);var l=jb(k);if(5===b)return a.ja?a.ja(c,d,e,g,h):a.call(null,c,d,e,g,h);k=O(l);var m=jb(l);if(6===b)return a.Da?a.Da(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);l=
O(m);var q=jb(m);if(7===b)return a.Ea?a.Ea(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);m=O(q);var n=jb(q);if(8===b)return a.Fa?a.Fa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);q=O(n);var r=jb(n);if(9===b)return a.Ga?a.Ga(c,d,e,g,h,k,l,m,q):a.call(null,c,d,e,g,h,k,l,m,q);n=O(r);var t=jb(r);if(10===b)return a.sa?a.sa(c,d,e,g,h,k,l,m,q,n):a.call(null,c,d,e,g,h,k,l,m,q,n);r=O(t);var u=jb(t);if(11===b)return a.ta?a.ta(c,d,e,g,h,k,l,m,q,n,r):a.call(null,c,d,e,g,h,k,l,m,q,n,r);t=O(u);var z=jb(u);if(12===
b)return a.ua?a.ua(c,d,e,g,h,k,l,m,q,n,r,t):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t);u=O(z);var B=jb(z);if(13===b)return a.va?a.va(c,d,e,g,h,k,l,m,q,n,r,t,u):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u);z=O(B);var N=jb(B);if(14===b)return a.wa?a.wa(c,d,e,g,h,k,l,m,q,n,r,t,u,z):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z);B=O(N);var W=jb(N);if(15===b)return a.xa?a.xa(c,d,e,g,h,k,l,m,q,n,r,t,u,z,B):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B);N=O(W);var ca=jb(W);if(16===b)return a.ya?a.ya(c,d,e,g,h,k,l,m,q,n,r,t,u,
z,B,N):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N);W=O(ca);var sa=jb(ca);if(17===b)return a.za?a.za(c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W);ca=O(sa);var Ha=jb(sa);if(18===b)return a.Aa?a.Aa(c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca);sa=O(Ha);Ha=jb(Ha);if(19===b)return a.Ba?a.Ba(c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa);var ja=O(Ha);jb(Ha);if(20===b)return a.Ca?
a.Ca(c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa,ja):a.call(null,c,d,e,g,h,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa,ja);throw Error("Only up to 20 arguments supported on functions");}function Ed(a){return null!=a&&(a.h&128||D===a.Wa)?a.W():Q(mc(a))}function Fd(a,b,c){return null==c?a.a?a.a(b):a.call(a,b):Gd(a,b,O(c),Ed(c))}function Gd(a,b,c,d){return null==d?a.b?a.b(b,c):a.call(a,b,c):Hd(a,b,c,O(d),Ed(d))}function Hd(a,b,c,d,e){return null==e?a.g?a.g(b,c,d):a.call(a,b,c,d):Id(a,b,c,d,O(e),Ed(e))}
function Id(a,b,c,d,e,g){if(null==g)return a.V?a.V(b,c,d,e):a.call(a,b,c,d,e);var h=O(g),k=T(g);if(null==k)return a.ja?a.ja(b,c,d,e,h):a.call(a,b,c,d,e,h);g=O(k);var l=T(k);if(null==l)return a.Da?a.Da(b,c,d,e,h,g):a.call(a,b,c,d,e,h,g);k=O(l);var m=T(l);if(null==m)return a.Ea?a.Ea(b,c,d,e,h,g,k):a.call(a,b,c,d,e,h,g,k);l=O(m);var q=T(m);if(null==q)return a.Fa?a.Fa(b,c,d,e,h,g,k,l):a.call(a,b,c,d,e,h,g,k,l);m=O(q);var n=T(q);if(null==n)return a.Ga?a.Ga(b,c,d,e,h,g,k,l,m):a.call(a,b,c,d,e,h,g,k,l,m);
q=O(n);var r=T(n);if(null==r)return a.sa?a.sa(b,c,d,e,h,g,k,l,m,q):a.call(a,b,c,d,e,h,g,k,l,m,q);n=O(r);var t=T(r);if(null==t)return a.ta?a.ta(b,c,d,e,h,g,k,l,m,q,n):a.call(a,b,c,d,e,h,g,k,l,m,q,n);r=O(t);var u=T(t);if(null==u)return a.ua?a.ua(b,c,d,e,h,g,k,l,m,q,n,r):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r);t=O(u);var z=T(u);if(null==z)return a.va?a.va(b,c,d,e,h,g,k,l,m,q,n,r,t):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t);u=O(z);var B=T(z);if(null==B)return a.wa?a.wa(b,c,d,e,h,g,k,l,m,q,n,r,t,u):a.call(a,b,c,d,
e,h,g,k,l,m,q,n,r,t,u);z=O(B);var N=T(B);if(null==N)return a.xa?a.xa(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t,u,z);B=O(N);var W=T(N);if(null==W)return a.ya?a.ya(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B);N=O(W);var ca=T(W);if(null==ca)return a.za?a.za(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N);W=O(ca);var sa=T(ca);if(null==sa)return a.Aa?a.Aa(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W):a.call(a,b,c,d,e,h,g,k,l,m,
q,n,r,t,u,z,B,N,W);ca=O(sa);var Ha=T(sa);if(null==Ha)return a.Ba?a.Ba(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W,ca):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W,ca);sa=O(Ha);Ha=T(Ha);if(null==Ha)return a.Ca?a.Ca(b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa):a.call(a,b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa);b=[b,c,d,e,h,g,k,l,m,q,n,r,t,u,z,B,N,W,ca,sa];for(c=Ha;;)if(c)b.push(O(c)),c=T(c);else break;return a.apply(a,b)}
function Sc(a){switch(arguments.length){case 2:return Jd(arguments[0],arguments[1]);case 3:return Kd(arguments[0],arguments[1],arguments[2]);case 4:var b=arguments[0];var c=arguments[1],d=arguments[2],e=arguments[3];b.I?(c=Hc(c,Hc(d,e)),d=b.P,e=2+Ad(d-1,e),b=e<=d?Dd(b,e,c):b.I(c)):b=Gd(b,c,d,Q(e));return b;case 5:b=arguments[0];c=arguments[1];d=arguments[2];var g=arguments[3];e=arguments[4];b.I?(c=Hc(c,Hc(d,Hc(g,e))),d=b.P,e=3+Ad(d-2,e),b=e<=d?Dd(b,e,c):b.I(c)):b=Hd(b,c,d,g,Q(e));return b;default:e=
[];b=arguments.length;for(c=0;;)if(c<b)e.push(arguments[c]),c+=1;else break;b=arguments[0];c=arguments[1];d=arguments[2];g=arguments[3];var h=arguments[4];e=new lc(e.slice(5),0,null);b.I?(e=Bd(e),c=Hc(c,Hc(d,Hc(g,Hc(h,e)))),d=b.P,e=4+Ad(d-3,e),b=e<=d?Dd(b,e,c):b.I(c)):b=Id(b,c,d,g,h,Bd(e));return b}}function Jd(a,b){if(a.I){var c=a.P,d=Ad(c+1,b);return d<=c?Dd(a,d,b):a.I(b)}b=Q(b);return null==b?a.B?a.B():a.call(a):Fd(a,O(b),Ed(b))}
function Kd(a,b,c){if(a.I){b=Hc(b,c);var d=a.P;c=Ad(d,c)+1;return c<=d?Dd(a,c,b):a.I(b)}return Fd(a,b,Q(c))}
function Ld(){if("undefined"===typeof Da||"undefined"===typeof Ea||"undefined"===typeof p)p=function(a){this.C=a;this.h=393216;this.o=0},p.prototype.O=function(a,b){return new p(b)},p.prototype.M=function(){return this.C},p.prototype.fa=function(){return!1},p.prototype.next=function(){return Error("No such element")},p.prototype.remove=function(){return Error("Unsupported operation")},p.$b=function(){return new Md(null,1,5,Nd,[y],null)},p.ub=!0,p.gb="cljs.core/t_cljs$core6274",p.Lb=function(a){return Jb(a,
"cljs.core/t_cljs$core6274")};return new p(Pd)}function Qd(a,b){for(;;){if(null==Q(b))return!0;var c=S(b);c=a.a?a.a(c):a.call(null,c);if(E(c))b=T(b);else return!1}}
var Rd=function Rd(a){switch(arguments.length){case 1:return Rd.a(arguments[0]);case 2:return Rd.b(arguments[0],arguments[1]);case 3:return Rd.g(arguments[0],arguments[1],arguments[2]);case 4:return Rd.V(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Rd.w(arguments[0],arguments[1],arguments[2],arguments[3],new lc(c.slice(4),0,null))}};
Rd.a=function(a){return function(b){return function(){function c(k,l){l=a.a?a.a(l):a.call(null,l);return b.b?b.b(k,l):b.call(null,k,l)}function d(k){return b.a?b.a(k):b.call(null,k)}function e(){return b.B?b.B():b.call(null)}var g=null,h=function(){function k(m,q,n){var r=null;if(2<arguments.length){r=0;for(var t=Array(arguments.length-2);r<t.length;)t[r]=arguments[r+2],++r;r=new lc(t,0,null)}return l.call(this,m,q,r)}function l(m,q,n){q=Kd(a,q,n);return b.b?b.b(m,q):b.call(null,m,q)}k.P=2;k.I=function(m){var q=
S(m);m=T(m);var n=S(m);m=mc(m);return l(q,n,m)};k.w=l;return k}();g=function(k,l,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,l);default:var q=null;if(2<arguments.length){q=0;for(var n=Array(arguments.length-2);q<n.length;)n[q]=arguments[q+2],++q;q=new lc(n,0,null)}return h.w(k,l,q)}throw Error("Invalid arity: "+arguments.length);};g.P=2;g.I=h.I;g.B=e;g.a=d;g.b=c;g.w=h.w;return g}()}};
Rd.b=function(a,b){return new td(null,function(){var c=Q(b);if(c){if(ad(c)){for(var d=Rb(c),e=X(d),g=new vd(Array(e)),h=0;;)if(h<e)zd(g,function(){var k=hb(d,h);return a.a?a.a(k):a.call(null,k)}()),h+=1;else break;return yd(g.ra(),Rd.b(a,Sb(c)))}return Hc(function(){var k=S(c);return a.a?a.a(k):a.call(null,k)}(),Rd.b(a,mc(c)))}return null},null)};
Rd.g=function(a,b,c){return new td(null,function(){var d=Q(b),e=Q(c);if(d&&e){var g=S(d);var h=S(e);g=a.b?a.b(g,h):a.call(null,g,h);d=Hc(g,Rd.g(a,mc(d),mc(e)))}else d=null;return d},null)};Rd.V=function(a,b,c,d){return new td(null,function(){var e=Q(b),g=Q(c),h=Q(d);if(e&&g&&h){var k=S(e);var l=S(g),m=S(h);k=a.g?a.g(k,l,m):a.call(null,k,l,m);e=Hc(k,Rd.V(a,mc(e),mc(g),mc(h)))}else e=null;return e},null)};
Rd.w=function(a,b,c,d,e){return Rd.b(function(g){return Jd(a,g)},function k(h){return new td(null,function(){var l=Rd.b(Q,h);return Qd(kd,l)?Hc(Rd.b(S,l),k(Rd.b(mc,l))):null},null)}(Jc.w(e,d,Ic([c,b]))))};Rd.I=function(a){var b=S(a),c=T(a);a=S(c);var d=T(c);c=S(d);var e=T(d);d=S(e);e=T(e);return this.w(b,a,c,d,e)};Rd.P=4;function Sd(a,b,c){return null!=a&&(a.o&4||D===a.yb)?wb(Ob(ld(b,Cd,Mb(a),c)),Uc(a)):ld(b,Jc,a,c)}function Td(a,b){this.A=a;this.c=b}
function Ud(a){return new Td(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Vd(a){a=a.i;return 32>a?0:a-1>>>5<<5}function Wd(a,b,c){for(;;){if(0===b)return c;var d=Ud(a);d.c[0]=c;c=d;b-=5}}var Xd=function Xd(a,b,c,d){var g=new Td(c.A,Xa(c.c)),h=a.i-1>>>b&31;5===b?g.c[h]=d:(c=c.c[h],null!=c?(b-=5,a=Xd.V?Xd.V(a,b,c,d):Xd.call(null,a,b,c,d)):a=Wd(null,b-5,d),g.c[h]=a);return g};
function Yd(a,b){if(b>=Vd(a))return a.Z;var c=a.root;for(a=a.shift;;)if(0<a){var d=a-5;c=c.c[b>>>a&31];a=d}else return c.c}function Zd(a,b){if(0<=b&&b<a.i)b=Yd(a,b);else throw a=a.i,Error(["No item ",K.a(b)," in vector of length ",K.a(a)].join(""));return b}var $d=function $d(a,b,c,d,e){var h=new Td(c.A,Xa(c.c));if(0===b)h.c[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.c[k];a=$d.ja?$d.ja(a,b,c,d,e):$d.call(null,a,b,c,d,e);h.c[k]=a}return h};
function ae(a,b,c){this.hb=this.j=0;this.c=a;this.Ob=b;this.start=0;this.end=c}ae.prototype.fa=function(){return this.j<this.end};ae.prototype.next=function(){32===this.j-this.hb&&(this.c=Yd(this.Ob,this.j),this.hb+=32);var a=this.c[this.j&31];this.j+=1;return a};function be(a,b,c,d){return c<d?ce(a,b,Dc(a,c),c+1,d):b.B?b.B():b.call(null)}
function ce(a,b,c,d,e){var g=c;c=d;for(d=Yd(a,d);;)if(c<e){var h=c&31;d=0===h?Yd(a,c):d;h=d[h];g=b.b?b.b(g,h):b.call(null,g,h);if(wc(g))return tb(g);c+=1}else return g}function Md(a,b,c,d,e,g){this.l=a;this.i=b;this.shift=c;this.root=d;this.Z=e;this.m=g;this.h=167666463;this.o=139268}f=Md.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.K=function(a,b){return this.v(null,b,null)};f.v=function(a,b,c){return"number"===typeof b?this.$(null,b,c):c};
f.eb=function(a,b,c){a=0;for(var d=c;;)if(a<this.i){var e=Yd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=g+a,k=e[g];d=b.g?b.g(d,h,k):b.call(null,d,h,k);if(wc(d)){e=d;break a}g+=1}else{e=d;break a}if(wc(e))return tb(e);a+=c;d=e}else return d};f.T=function(a,b){return Zd(this,b)[b&31]};f.$=function(a,b,c){return 0<=b&&b<this.i?Yd(this,b)[b&31]:c};
f.kb=function(a,b){if(0<=a&&a<this.i){if(Vd(this)<=a){var c=Xa(this.Z);c[a&31]=b;return new Md(this.l,this.i,this.shift,this.root,c,null)}return new Md(this.l,this.i,this.shift,$d(this,this.shift,this.root,a,b),this.Z,null)}if(a===this.i)return this.U(null,b);throw Error(["Index ",K.a(a)," out of bounds  [0,",K.a(this.i),"]"].join(""));};f.qa=function(){var a=this.i;return new ae(0<X(this)?Yd(this,0):null,this,a)};f.M=function(){return this.l};f.da=function(){return this.i};
f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){if(b instanceof Md)if(this.i===X(b))for(a=this.qa(null),b=b.qa(null);;)if(a.fa()){var c=a.next(),d=b.next();if(!oc.b(c,d))return!1}else return!0;else return!1;else return Gc(this,b)};f.Va=function(){return new de(this.i,this.shift,ee.a?ee.a(this.root):ee.call(null,this.root),fe.a?fe.a(this.Z):fe.call(null,this.Z))};f.X=function(){return wb(Kc,this.l)};f.ba=function(a,b){return be(this,b,0,this.i)};
f.ca=function(a,b,c){a=0;for(var d=c;;)if(a<this.i){var e=Yd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=e[g];d=b.b?b.b(d,h):b.call(null,d,h);if(wc(d)){e=d;break a}g+=1}else{e=d;break a}if(wc(e))return tb(e);a+=c;d=e}else return d};f.Ma=function(a,b,c){if("number"===typeof b)return this.kb(b,c);throw Error("Vector's key for assoc must be a number.");};
f.H=function(){if(0===this.i)return null;if(32>=this.i)return new lc(this.Z,0,null);a:{var a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.c[0];else{a=a.c;break a}}return ge?ge(this,a,0,0):he.call(null,this,a,0,0)};f.O=function(a,b){return b===this.l?this:new Md(b,this.i,this.shift,this.root,this.Z,this.m)};
f.U=function(a,b){if(32>this.i-Vd(this)){a=this.Z.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.Z[d],d+=1;else break;c[a]=b;return new Md(this.l,this.i+1,this.shift,this.root,c,null)}a=(c=this.i>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=Ud(null),c.c[0]=this.root,d=Wd(null,this.shift,new Td(null,this.Z)),c.c[1]=d):c=Xd(this,this.shift,this.root,new Td(null,this.Z));return new Md(this.l,this.i+1,a,c,[b],null)};
f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.a=function(a){return this.T(null,a)};f.b=function(a,b){return this.$(null,a,b)};
var Nd=new Td(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Kc=new Md(null,0,5,Nd,[],sc);Md.prototype[Wa]=function(){return qc(this)};function ie(a,b,c,d,e){this.ia=a;this.node=b;this.j=c;this.R=d;this.l=e;this.m=null;this.h=32375020;this.o=1536}f=ie.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){if(this.R+1<this.node.length){var a=this.ia;var b=this.node,c=this.j,d=this.R+1;a=ge?ge(a,b,c,d):he.call(null,a,b,c,d);return null==a?null:a}return this.nb()};
f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ba=function(a,b){return be(this.ia,b,this.j+this.R,X(this.ia))};f.ca=function(a,b,c){return ce(this.ia,b,c,this.j+this.R,X(this.ia))};f.ea=function(){return this.node[this.R]};f.ha=function(){if(this.R+1<this.node.length){var a=this.ia;var b=this.node,c=this.j,d=this.R+1;a=ge?ge(a,b,c,d):he.call(null,a,b,c,d);return null==a?nc:a}return this.bb(null)};f.H=function(){return this};
f.jb=function(){var a=this.node;return new wd(a,this.R,a.length)};f.bb=function(){var a=this.j+this.node.length;if(a<bb(this.ia)){var b=this.ia,c=Yd(this.ia,a);return ge?ge(b,c,a,0):he.call(null,b,c,a,0)}return nc};f.O=function(a,b){return b===this.l?this:je?je(this.ia,this.node,this.j,this.R,b):he.call(null,this.ia,this.node,this.j,this.R,b)};f.U=function(a,b){return Hc(b,this)};
f.nb=function(){var a=this.j+this.node.length;if(a<bb(this.ia)){var b=this.ia,c=Yd(this.ia,a);return ge?ge(b,c,a,0):he.call(null,b,c,a,0)}return null};ie.prototype[Wa]=function(){return qc(this)};
function he(a){switch(arguments.length){case 3:var b=arguments[0],c=arguments[1],d=arguments[2];return new ie(b,Zd(b,c),c,d,null);case 4:return ge(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return je(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}function ge(a,b,c,d){return new ie(a,b,c,d,null)}function je(a,b,c,d,e){return new ie(a,b,c,d,e)}
function ke(a,b){return a===b.A?b:new Td(a,Xa(b.c))}function ee(a){return new Td({},Xa(a.c))}function fe(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];bd(a,0,b,0,a.length);return b}var le=function le(a,b,c,d){c=ke(a.root.A,c);var g=a.i-1>>>b&31;if(5===b)a=d;else{var h=c.c[g];null!=h?(b-=5,a=le.V?le.V(a,b,h,d):le.call(null,a,b,h,d)):a=Wd(a.root.A,b-5,d)}c.c[g]=a;return c};
function de(a,b,c,d){this.i=a;this.shift=b;this.root=c;this.Z=d;this.o=88;this.h=275}f=de.prototype;
f.Xa=function(a,b){if(this.root.A){if(32>this.i-Vd(this))this.Z[this.i&31]=b;else{a=new Td(this.root.A,this.Z);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.Z=c;this.i>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+5,b[0]=
this.root,b[1]=Wd(this.root.A,this.shift,a),this.root=new Td(this.root.A,b),this.shift=c):this.root=le(this,this.shift,this.root,a)}this.i+=1;return this}throw Error("conj! after persistent!");};f.fb=function(){if(this.root.A){this.root.A=null;var a=this.i-Vd(this),b=Array(a);bd(this.Z,0,b,0,a);return new Md(null,this.i,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Ta=function(a,b,c){if("number"===typeof b)return me(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
function me(a,b,c){if(a.root.A){if(0<=b&&b<a.i){if(Vd(a)<=b)a.Z[b&31]=c;else{var d=function k(g,h){h=ke(a.root.A,h);if(0===g)h.c[b&31]=c;else{var l=b>>>g&31;g=k(g-5,h.c[l]);h.c[l]=g}return h}(a.shift,a.root);a.root=d}return a}if(b===a.i)return a.Xa(null,c);throw Error(["Index ",K.a(b)," out of bounds for TransientVector of length",K.a(a.i)].join(""));}throw Error("assoc! after persistent!");}f.da=function(){if(this.root.A)return this.i;throw Error("count after persistent!");};
f.T=function(a,b){if(this.root.A)return Zd(this,b)[b&31];throw Error("nth after persistent!");};f.$=function(a,b,c){return 0<=b&&b<this.i?this.T(null,b):c};f.K=function(a,b){return this.v(null,b,null)};f.v=function(a,b,c){if(this.root.A)return"number"===typeof b?this.$(null,b,c):c;throw Error("lookup after persistent!");};
f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.a=function(a){return this.K(null,a)};f.b=function(a,b){return this.v(null,a,b)};function ne(){this.h=2097152;this.o=0}ne.prototype.G=function(){return!1};var oe=new ne;
function pe(a,b){return ed(Xc(b)&&!Zc(b)?X(a)===X(b)?(null!=a?a.h&1048576||D===a.Ub||(a.h?0:F(Ab,a)):F(Ab,a))?jd(function(c,d,e){return oc.b(jc.g(b,d,oe),e)?!0:new vc},a):Qd(function(c){return oc.b(jc.g(b,S(c),oe),S(T(c)))},a):null:null)}function qe(a){this.u=a}qe.prototype.next=function(){if(null!=this.u){var a=S(this.u),b=Oc(a,0,null);a=Oc(a,1,null);this.u=T(this.u);return{value:[b,a],done:!1}}return{value:null,done:!0}};
function re(a,b){if(b instanceof qd)a:{var c=a.length;b=b.Ja;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof qd&&b===a[d].Ja){a=d;break a}d+=2}}else if("string"==typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}else if(b instanceof ic)a:for(c=a.length,b=b.Ka,d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof ic&&b===a[d].Ka){a=d;break a}d+=2}else if(null==b)a:for(b=a.length,c=0;;){if(b<=c){a=-1;break a}if(null==a[c]){a=c;break a}c+=2}else a:for(c=
a.length,d=0;;){if(c<=d){a=-1;break a}if(oc.b(b,a[d])){a=d;break a}d+=2}return a}function se(a,b){this.key=a;this.F=b;this.m=null;this.h=166619935;this.o=0}f=se.prototype;f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.K=function(a,b){return this.$(null,b,null)};f.v=function(a,b,c){return this.$(null,b,c)};f.T=function(a,b){if(0===b)return this.key;if(1===b)return this.F;throw Error("Index out of bounds");};
f.$=function(a,b,c){return 0===b?this.key:1===b?this.F:c};f.kb=function(a,b){return(new Md(null,2,5,Nd,[this.key,this.F],null)).kb(a,b)};f.M=function(){return null};f.da=function(){return 2};f.Fb=function(){return this.key};f.Gb=function(){return this.F};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};f.X=function(){return null};
f.ba=function(a,b){a:if(a=this.da(null),0===a)b=b.B?b.B():b.call(null);else for(var c=this.T(null,0),d=1;;)if(d<a){var e=this.T(null,d);c=b.b?b.b(c,e):b.call(null,c,e);if(wc(c)){b=tb(c);break a}d+=1}else{b=c;break a}return b};f.ca=function(a,b,c){a:{a=this.da(null);var d=c;for(c=0;;)if(c<a){var e=this.T(null,c);d=b.b?b.b(d,e):b.call(null,d,e);if(wc(d)){b=tb(d);break a}c+=1}else{b=d;break a}}return b};f.Ma=function(a,b,c){return Pc.g(new Md(null,2,5,Nd,[this.key,this.F],null),b,c)};
f.H=function(){return new lc([this.key,this.F],0,null)};f.O=function(a,b){return Tc(new Md(null,2,5,Nd,[this.key,this.F],null),b)};f.U=function(a,b){return new Md(null,3,5,Nd,[this.key,this.F,b],null)};f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};
f.a=function(a){return this.T(null,a)};f.b=function(a,b){return this.$(null,a,b)};function te(a){return null!=a?a.h&2048||D===a.Xb?!0:!1:!1}function ue(a,b,c){this.c=a;this.j=b;this.pa=c;this.h=32374990;this.o=0}f=ue.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.pa};f.W=function(){return this.j<this.c.length-2?new ue(this.c,this.j+2,null):null};f.da=function(){return(this.c.length-this.j)/2};f.S=function(){return rc(this)};
f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return new se(this.c[this.j],this.c[this.j+1])};f.ha=function(){return this.j<this.c.length-2?new ue(this.c,this.j+2,null):nc};f.H=function(){return this};f.O=function(a,b){return b===this.pa?this:new ue(this.c,this.j,b)};f.U=function(a,b){return Hc(b,this)};ue.prototype[Wa]=function(){return qc(this)};
function ve(a,b){this.c=a;this.j=0;this.i=b}ve.prototype.fa=function(){return this.j<this.i};ve.prototype.next=function(){var a=new se(this.c[this.j],this.c[this.j+1]);this.j+=2;return a};function Na(a,b,c,d){this.l=a;this.i=b;this.c=c;this.m=d;this.h=16647951;this.o=139268}f=Na.prototype;f.toString=function(){return Yb(this)};f.keys=function(){return qc(we.a?we.a(this):we.call(null,this))};f.entries=function(){return new qe(Q(Q(this)))};
f.values=function(){return qc(xe.a?xe.a(this):xe.call(null,this))};f.has=function(a){return jc.g(this,a,cd)===cd?!1:!0};f.get=function(a,b){return this.v(null,a,b)};f.forEach=function(a){for(var b=Q(this),c=null,d=0,e=0;;)if(e<d){var g=c.T(null,e),h=Oc(g,0,null);g=Oc(g,1,null);a.b?a.b(g,h):a.call(null,g,h);e+=1}else if(b=Q(b))ad(b)?(c=Rb(b),b=Sb(b),h=c,d=X(c),c=h):(c=S(b),h=Oc(c,0,null),g=Oc(c,1,null),a.b?a.b(g,h):a.call(null,g,h),b=T(b),c=null,d=0),e=0;else return null};
f.K=function(a,b){return this.v(null,b,null)};f.v=function(a,b,c){a=re(this.c,b);return-1===a?c:this.c[a+1]};f.eb=function(a,b,c){a=this.c.length;for(var d=0;;)if(d<a){var e=this.c[d],g=this.c[d+1];c=b.g?b.g(c,e,g):b.call(null,c,e,g);if(wc(c))return tb(c);d+=2}else return c};f.qa=function(){return new ve(this.c,2*this.i)};f.M=function(){return this.l};f.da=function(){return this.i};f.S=function(){var a=this.m;return null!=a?a:this.m=a=tc(this)};
f.G=function(a,b){if(Xc(b)&&!Zc(b))if(a=this.c.length,this.i===b.da(null))for(var c=0;;)if(c<a){var d=b.v(null,this.c[c],cd);if(d!==cd)if(oc.b(this.c[c+1],d))c+=2;else return!1;else return!1}else return!0;else return!1;else return!1};f.Va=function(){return new ye(this.c.length,Xa(this.c))};f.X=function(){return wb(Pd,this.l)};f.ba=function(a,b){return hd(this,b)};f.ca=function(a,b,c){return id(this,b,c)};
f.Ma=function(a,b,c){a=re(this.c,b);if(-1===a){if(this.i<ze){a=this.c;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new Na(this.l,this.i+1,e,null)}a=Ae;a=null!=a?null!=a&&(a.o&4||D===a.yb)?wb(Ob(Za(Nb,Mb(a),this)),Uc(a)):Za(fb,a,this):Za(Jc,a,this);return wb(ob(a,b,c),this.l)}if(c===this.c[a+1])return this;b=Xa(this.c);b[a+1]=c;return new Na(this.l,this.i,b,null)};f.H=function(){var a=this.c;return 0<=a.length-2?new ue(a,0,null):null};
f.O=function(a,b){return b===this.l?this:new Na(b,this.i,this.c,this.m)};f.U=function(a,b){if($c(b))return this.Ma(null,hb(b,0),hb(b,1));a=this;for(b=Q(b);;){if(null==b)return a;var c=S(b);if($c(c))a=ob(a,hb(c,0),hb(c,1)),b=T(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.a=function(a){return this.K(null,a)};f.b=function(a,b){return this.v(null,a,b)};var Pd=new Na(null,0,[],uc),ze=8;
function Qc(a){for(var b=[],c=0;;)if(c<a.length){var d=a[c],e=a[c+1],g=re(b,d);-1===g?(g=b,g.push(d),g.push(e)):b[g+1]=e;c+=2}else break;return new Na(null,b.length/2,b,null)}Na.prototype[Wa]=function(){return qc(this)};function ye(a,b){this.Ua={};this.Qa=a;this.c=b;this.h=259;this.o=56}f=ye.prototype;f.da=function(){if(this.Ua)return md(this.Qa);throw Error("count after persistent!");};f.K=function(a,b){return this.v(null,b,null)};
f.v=function(a,b,c){if(this.Ua)return a=re(this.c,b),-1===a?c:this.c[a+1];throw Error("lookup after persistent!");};f.Xa=function(a,b){if(this.Ua){if(te(b))return this.Ta(null,Be.a?Be.a(b):Be.call(null,b),Ce.a?Ce.a(b):Ce.call(null,b));if($c(b))return this.Ta(null,b.a?b.a(0):b.call(null,0),b.a?b.a(1):b.call(null,1));a=Q(b);for(b=this;;){var c=S(a);if(E(c))a=T(a),b=Pb(b,Be.a?Be.a(c):Be.call(null,c),Ce.a?Ce.a(c):Ce.call(null,c));else return b}}else throw Error("conj! after persistent!");};
f.fb=function(){if(this.Ua)return this.Ua=!1,new Na(null,md(this.Qa),this.c,null);throw Error("persistent! called twice");};f.Ta=function(a,b,c){if(this.Ua){a=re(this.c,b);if(-1===a){if(this.Qa+2<=2*ze)return this.Qa+=2,this.c.push(b),this.c.push(c),this;a=De.b?De.b(this.Qa,this.c):De.call(null,this.Qa,this.c);return Pb(a,b,c)}c!==this.c[a+1]&&(this.c[a+1]=c);return this}throw Error("assoc! after persistent!");};
f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.a=function(a){return this.v(null,a,null)};f.b=function(a,b){return this.v(null,a,b)};function De(a,b){for(var c=Mb(Ae),d=0;;)if(d<a)c=Pb(c,b[d],b[d+1]),d+=2;else return c}function Ee(){this.F=!1}
function Fe(a,b){return a===b?!0:a===b||a instanceof qd&&b instanceof qd&&a.Ja===b.Ja?!0:oc.b(a,b)}function Ge(a,b,c){a=Xa(a);a[b]=c;return a}function He(a,b,c,d){a=a.Oa(b);a.c[c]=d;return a}function Ie(a,b,c){for(var d=a.length,e=0,g=c;;)if(e<d){c=a[e];if(null!=c){var h=a[e+1];c=b.g?b.g(g,c,h):b.call(null,g,c,h)}else c=a[e+1],c=null!=c?c.$a(b,g):g;if(wc(c))return c;e+=2;g=c}else return g}function Je(a){this.c=a;this.j=0;this.na=this.ab=null}
Je.prototype.advance=function(){for(var a=this.c.length;;)if(this.j<a){var b=this.c[this.j],c=this.c[this.j+1];null!=b?b=this.ab=new se(b,c):null!=c?(b=Wb(c),b=b.fa()?this.na=b:!1):b=!1;this.j+=2;if(b)return!0}else return!1};Je.prototype.fa=function(){var a=null!=this.ab;return a?a:(a=null!=this.na)?a:this.advance()};
Je.prototype.next=function(){if(null!=this.ab){var a=this.ab;this.ab=null;return a}if(null!=this.na)return a=this.na.next(),this.na.fa()||(this.na=null),a;if(this.advance())return this.next();throw Error("No such element");};Je.prototype.remove=function(){return Error("Unsupported operation")};function Ke(a,b,c){this.A=a;this.J=b;this.c=c;this.o=131072;this.h=0}f=Ke.prototype;
f.Oa=function(a){if(a===this.A)return this;var b=nd(this.J),c=Array(0>b?4:2*(b+1));bd(this.c,0,c,0,2*b);return new Ke(a,this.J,c)};f.Za=function(){return Le?Le(this.c):Me.call(null,this.c)};f.$a=function(a,b){return Ie(this.c,a,b)};f.Pa=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.J&e))return d;var g=nd(this.J&e-1);e=this.c[2*g];g=this.c[2*g+1];return null==e?g.Pa(a+5,b,c,d):Fe(c,e)?g:d};
f.la=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=nd(this.J&h-1);if(0===(this.J&h)){var l=nd(this.J);if(2*l<this.c.length){a=this.Oa(a);b=a.c;g.F=!0;c=2*(l-k);g=2*k+(c-1);for(l=2*(k+1)+(c-1);0!==c;)b[l]=b[g],--l,--c,--g;b[2*k]=d;b[2*k+1]=e;a.J|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Ne.la(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0===(this.J>>>d&1)?
d+=1:(k[d]=null!=this.c[e]?Ne.la(a,b+5,gc(this.c[e]),this.c[e],this.c[e+1],g):this.c[e+1],e+=2,d+=1);else break;return new Oe(a,l+1,k)}b=Array(2*(l+4));bd(this.c,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;bd(this.c,2*k,b,2*(k+1),2*(l-k));g.F=!0;a=this.Oa(a);a.c=b;a.J|=h;return a}l=this.c[2*k];h=this.c[2*k+1];if(null==l)return l=h.la(a,b+5,c,d,e,g),l===h?this:He(this,a,2*k+1,l);if(Fe(d,l))return e===h?this:He(this,a,2*k+1,e);g.F=!0;g=b+5;d=Pe?Pe(a,g,l,h,c,d,e):Qe.call(null,a,g,l,h,c,d,e);e=2*k;k=2*k+1;a=this.Oa(a);
a.c[e]=null;a.c[k]=d;return a};
f.ka=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=nd(this.J&g-1);if(0===(this.J&g)){var k=nd(this.J);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Ne.ka(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0===(this.J>>>c&1)?c+=1:(h[c]=null!=this.c[d]?Ne.ka(a+5,gc(this.c[d]),this.c[d],this.c[d+1],e):this.c[d+1],d+=2,c+=1);else break;return new Oe(null,k+1,h)}a=Array(2*(k+1));bd(this.c,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;bd(this.c,2*h,a,2*(h+1),2*(k-h));e.F=!0;return new Ke(null,this.J|g,a)}var l=this.c[2*h];g=this.c[2*h+1];if(null==l)return k=g.ka(a+5,b,c,d,e),k===g?this:new Ke(null,this.J,Ge(this.c,2*h+1,k));if(Fe(c,l))return d===g?this:new Ke(null,this.J,Ge(this.c,2*h+1,d));e.F=!0;e=this.J;k=this.c;a+=5;a=Re?Re(a,l,g,b,c,d):Qe.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=Xa(k);d[c]=null;d[h]=a;return new Ke(null,e,d)};f.qa=function(){return new Je(this.c)};var Ne=new Ke(null,0,[]);
function Se(a){this.c=a;this.j=0;this.na=null}Se.prototype.fa=function(){for(var a=this.c.length;;){if(null!=this.na&&this.na.fa())return!0;if(this.j<a){var b=this.c[this.j];this.j+=1;null!=b&&(this.na=Wb(b))}else return!1}};Se.prototype.next=function(){if(this.fa())return this.na.next();throw Error("No such element");};Se.prototype.remove=function(){return Error("Unsupported operation")};function Oe(a,b,c){this.A=a;this.i=b;this.c=c;this.o=131072;this.h=0}f=Oe.prototype;
f.Oa=function(a){return a===this.A?this:new Oe(a,this.i,Xa(this.c))};f.Za=function(){return Te?Te(this.c):Ue.call(null,this.c)};f.$a=function(a,b){for(var c=this.c.length,d=0;;)if(d<c){var e=this.c[d];if(null!=e){b=e.$a(a,b);if(wc(b))return b;d+=1}else d+=1}else return b};f.Pa=function(a,b,c,d){var e=this.c[b>>>a&31];return null!=e?e.Pa(a+5,b,c,d):d};
f.la=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.c[h];if(null==k)return a=He(this,a,h,Ne.la(a,b+5,c,d,e,g)),a.i+=1,a;b=k.la(a,b+5,c,d,e,g);return b===k?this:He(this,a,h,b)};f.ka=function(a,b,c,d,e){var g=b>>>a&31,h=this.c[g];if(null==h)return new Oe(null,this.i+1,Ge(this.c,g,Ne.ka(a+5,b,c,d,e)));a=h.ka(a+5,b,c,d,e);return a===h?this:new Oe(null,this.i,Ge(this.c,g,a))};f.qa=function(){return new Se(this.c)};function Ve(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Fe(c,a[d]))return d;d+=2}else return-1}
function We(a,b,c,d){this.A=a;this.Ia=b;this.i=c;this.c=d;this.o=131072;this.h=0}f=We.prototype;f.Oa=function(a){if(a===this.A)return this;var b=Array(2*(this.i+1));bd(this.c,0,b,0,2*this.i);return new We(a,this.Ia,this.i,b)};f.Za=function(){return Le?Le(this.c):Me.call(null,this.c)};f.$a=function(a,b){return Ie(this.c,a,b)};f.Pa=function(a,b,c,d){a=Ve(this.c,this.i,c);return 0>a?d:Fe(c,this.c[a])?this.c[a+1]:d};
f.la=function(a,b,c,d,e,g){if(c===this.Ia){b=Ve(this.c,this.i,d);if(-1===b){if(this.c.length>2*this.i)return b=2*this.i,c=2*this.i+1,a=this.Oa(a),a.c[b]=d,a.c[c]=e,g.F=!0,a.i+=1,a;c=this.c.length;b=Array(c+2);bd(this.c,0,b,0,c);b[c]=d;b[c+1]=e;g.F=!0;d=this.i+1;a===this.A?(this.c=b,this.i=d,a=this):a=new We(this.A,this.Ia,d,b);return a}return this.c[b+1]===e?this:He(this,a,b+1,e)}return(new Ke(a,1<<(this.Ia>>>b&31),[null,this,null,null])).la(a,b,c,d,e,g)};
f.ka=function(a,b,c,d,e){return b===this.Ia?(a=Ve(this.c,this.i,c),-1===a?(a=2*this.i,b=Array(a+2),bd(this.c,0,b,0,a),b[a]=c,b[a+1]=d,e.F=!0,new We(null,this.Ia,this.i+1,b)):oc.b(this.c[a+1],d)?this:new We(null,this.Ia,this.i,Ge(this.c,a+1,d))):(new Ke(null,1<<(this.Ia>>>a&31),[null,this])).ka(a,b,c,d,e)};f.qa=function(){return new Je(this.c)};
function Qe(a){switch(arguments.length){case 6:return Re(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Pe(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}function Re(a,b,c,d,e,g){var h=gc(b);if(h===d)return new We(null,h,2,[b,c,e,g]);var k=new Ee;return Ne.ka(a,h,b,c,k).ka(a,d,e,g,k)}
function Pe(a,b,c,d,e,g,h){var k=gc(c);if(k===e)return new We(null,k,2,[c,d,g,h]);var l=new Ee;return Ne.la(a,b,k,c,d,l).la(a,b,e,g,h,l)}function Xe(a,b,c,d,e){this.l=a;this.oa=b;this.j=c;this.u=d;this.m=e;this.h=32374988;this.o=0}f=Xe.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){if(null==this.u){var a=this.oa,b=this.j+2;return Ye?Ye(a,b,null):Me.call(null,a,b,null)}a=this.oa;b=this.j;var c=T(this.u);return Ye?Ye(a,b,c):Me.call(null,a,b,c)};
f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return null==this.u?new se(this.oa[this.j],this.oa[this.j+1]):S(this.u)};
f.ha=function(){var a=this,b=null==a.u?function(){var c=a.oa,d=a.j+2;return Ye?Ye(c,d,null):Me.call(null,c,d,null)}():function(){var c=a.oa,d=a.j,e=T(a.u);return Ye?Ye(c,d,e):Me.call(null,c,d,e)}();return null!=b?b:nc};f.H=function(){return this};f.O=function(a,b){return b===this.l?this:new Xe(b,this.oa,this.j,this.u,this.m)};f.U=function(a,b){return Hc(b,this)};Xe.prototype[Wa]=function(){return qc(this)};
function Me(a){switch(arguments.length){case 1:return Le(arguments[0]);case 3:return Ye(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}function Le(a){return Ye(a,0,null)}function Ye(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Xe(null,a,b,null,null);var d=a[b+1];if(E(d)&&(d=d.Za(),E(d)))return new Xe(null,a,b+2,d,null);b+=2}else return null;else return new Xe(null,a,b,c,null)}
function Ze(a,b,c,d,e){this.l=a;this.oa=b;this.j=c;this.u=d;this.m=e;this.h=32374988;this.o=0}f=Ze.prototype;f.toString=function(){return Yb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.l};f.W=function(){var a=this.oa,b=this.j,c=T(this.u);return $e?$e(a,b,c):Ue.call(null,a,b,c)};f.S=function(){var a=this.m;return null!=a?a:this.m=a=rc(this)};f.G=function(a,b){return Gc(this,b)};
f.X=function(){return nc};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return S(this.u)};f.ha=function(){var a=this.oa;var b=this.j,c=T(this.u);a=$e?$e(a,b,c):Ue.call(null,a,b,c);return null!=a?a:nc};f.H=function(){return this};f.O=function(a,b){return b===this.l?this:new Ze(b,this.oa,this.j,this.u,this.m)};f.U=function(a,b){return Hc(b,this)};Ze.prototype[Wa]=function(){return qc(this)};
function Ue(a){switch(arguments.length){case 1:return Te(arguments[0]);case 3:return $e(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length)].join(""));}}function Te(a){return $e(a,0,null)}function $e(a,b,c){if(null==c)for(c=a.length;;)if(b<c){var d=a[b];if(E(d)&&(d=d.Za(),E(d)))return new Ze(null,a,b+1,d,null);b+=1}else return null;else return new Ze(null,a,b,c,null)}function af(a,b){this.Y=a;this.vb=b;this.lb=!1}
af.prototype.fa=function(){return!this.lb||this.vb.fa()};af.prototype.next=function(){if(this.lb)return this.vb.next();this.lb=!0;return new se(null,this.Y)};af.prototype.remove=function(){return Error("Unsupported operation")};function bf(a,b,c,d,e,g){this.l=a;this.i=b;this.root=c;this.ga=d;this.Y=e;this.m=g;this.h=16123663;this.o=139268}f=bf.prototype;f.toString=function(){return Yb(this)};f.keys=function(){return qc(we.a?we.a(this):we.call(null,this))};f.entries=function(){return new qe(Q(Q(this)))};
f.values=function(){return qc(xe.a?xe.a(this):xe.call(null,this))};f.has=function(a){return jc.g(this,a,cd)===cd?!1:!0};f.get=function(a,b){return this.v(null,a,b)};f.forEach=function(a){for(var b=Q(this),c=null,d=0,e=0;;)if(e<d){var g=c.T(null,e),h=Oc(g,0,null);g=Oc(g,1,null);a.b?a.b(g,h):a.call(null,g,h);e+=1}else if(b=Q(b))ad(b)?(c=Rb(b),b=Sb(b),h=c,d=X(c),c=h):(c=S(b),h=Oc(c,0,null),g=Oc(c,1,null),a.b?a.b(g,h):a.call(null,g,h),b=T(b),c=null,d=0),e=0;else return null};
f.K=function(a,b){return this.v(null,b,null)};f.v=function(a,b,c){return null==b?this.ga?this.Y:c:null==this.root?c:this.root.Pa(0,gc(b),b,c)};f.eb=function(a,b,c){a=this.ga?b.g?b.g(c,null,this.Y):b.call(null,c,null,this.Y):c;wc(a)?b=tb(a):null!=this.root?(b=this.root.$a(b,a),b=wc(b)?xc.a?xc.a(b):xc.call(null,b):b):b=a;return b};f.qa=function(){var a=this.root?Wb(this.root):Ld();return this.ga?new af(this.Y,a):a};f.M=function(){return this.l};f.da=function(){return this.i};
f.S=function(){var a=this.m;return null!=a?a:this.m=a=tc(this)};f.G=function(a,b){return pe(this,b)};f.Va=function(){return new cf(this.root,this.i,this.ga,this.Y)};f.X=function(){return wb(Ae,this.l)};f.Ma=function(a,b,c){if(null==b)return this.ga&&c===this.Y?this:new bf(this.l,this.ga?this.i:this.i+1,this.root,!0,c,null);a=new Ee;b=(null==this.root?Ne:this.root).ka(0,gc(b),b,c,a);return b===this.root?this:new bf(this.l,a.F?this.i+1:this.i,b,this.ga,this.Y,null)};
f.H=function(){if(0<this.i){var a=null!=this.root?this.root.Za():null;return this.ga?Hc(new se(null,this.Y),a):a}return null};f.O=function(a,b){return b===this.l?this:new bf(b,this.i,this.root,this.ga,this.Y,this.m)};f.U=function(a,b){if($c(b))return this.Ma(null,hb(b,0),hb(b,1));a=this;for(b=Q(b);;){if(null==b)return a;var c=S(b);if($c(c))a=ob(a,hb(c,0),hb(c,1)),b=T(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};f.a=function(a){return this.K(null,a)};f.b=function(a,b){return this.v(null,a,b)};var Ae=new bf(null,0,null,!1,null,uc);bf.prototype[Wa]=function(){return qc(this)};
function cf(a,b,c,d){this.A={};this.root=a;this.count=b;this.ga=c;this.Y=d;this.h=259;this.o=56}function df(a,b,c){if(a.A){if(null==b)a.Y!==c&&(a.Y=c),a.ga||(a.count+=1,a.ga=!0);else{var d=new Ee;b=(null==a.root?Ne:a.root).la(a.A,0,gc(b),b,c,d);b!==a.root&&(a.root=b);d.F&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=cf.prototype;f.da=function(){if(this.A)return this.count;throw Error("count after persistent!");};
f.K=function(a,b){return null==b?this.ga?this.Y:null:null==this.root?null:this.root.Pa(0,gc(b),b)};f.v=function(a,b,c){return null==b?this.ga?this.Y:c:null==this.root?c:this.root.Pa(0,gc(b),b,c)};
f.Xa=function(a,b){a:if(this.A)if(te(b))a=df(this,Be.a?Be.a(b):Be.call(null,b),Ce.a?Ce.a(b):Ce.call(null,b));else if($c(b))a=df(this,b.a?b.a(0):b.call(null,0),b.a?b.a(1):b.call(null,1));else for(a=Q(b),b=this;;){var c=S(a);if(E(c))a=T(a),b=df(b,Be.a?Be.a(c):Be.call(null,c),Ce.a?Ce.a(c):Ce.call(null,c));else{a=b;break a}}else throw Error("conj! after persistent");return a};
f.fb=function(){if(this.A){this.A=null;var a=new bf(null,this.count,this.root,this.ga,this.Y,null)}else throw Error("persistent! called twice");return a};f.Ta=function(a,b,c){return df(this,b,c)};f.call=function(a){switch(arguments.length-1){case 1:return this.a(arguments[1]);case 2:return this.b(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",K.a(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(Xa(b)))};
f.a=function(a){return this.K(null,a)};f.b=function(a,b){return this.v(null,a,b)};var ef=function ef(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ef.w(0<c.length?new lc(c.slice(0),0,null):null)};ef.w=function(a){for(var b=Q(a),c=Mb(Ae);;)if(b){a=T(T(b));var d=S(b);b=S(T(b));c=Pb(c,d,b);b=a}else return Ob(c)};ef.P=0;ef.I=function(a){return this.w(Q(a))};
var ff=function ff(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ff.w(0<c.length?new lc(c.slice(0),0,null):null)};ff.w=function(a){a=a instanceof lc&&0===a.j?a.c:Ya(a);return Qc(a)};ff.P=0;ff.I=function(a){return this.w(Q(a))};function gf(a,b){this.s=a;this.pa=b;this.h=32374988;this.o=0}f=gf.prototype;f.toString=function(){return Yb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.pa};f.W=function(){var a=(null!=this.s?this.s.h&128||D===this.s.Wa||(this.s.h?0:F(kb,this.s)):F(kb,this.s))?this.s.W():T(this.s);return null==a?null:new gf(a,null)};f.S=function(){return rc(this)};
f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return this.s.ea(null).key};f.ha=function(){var a=(null!=this.s?this.s.h&128||D===this.s.Wa||(this.s.h?0:F(kb,this.s)):F(kb,this.s))?this.s.W():T(this.s);return null!=a?new gf(a,null):nc};f.H=function(){return this};f.O=function(a,b){return b===this.pa?this:new gf(this.s,b)};f.U=function(a,b){return Hc(b,this)};gf.prototype[Wa]=function(){return qc(this)};
function we(a){return(a=Q(a))?new gf(a,null):null}function Be(a){return qb(a)}function hf(a,b){this.s=a;this.pa=b;this.h=32374988;this.o=0}f=hf.prototype;f.toString=function(){return Yb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V(this,b,0);case 2:return V(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.a=function(b){return V(this,b,0)};a.b=function(b,c){return V(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return Z(this,c,X(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.a=a;b.b=function(c,d){return Z(this,c,d)};return b}();f.M=function(){return this.pa};f.W=function(){var a=(null!=this.s?this.s.h&128||D===this.s.Wa||(this.s.h?0:F(kb,this.s)):F(kb,this.s))?this.s.W():T(this.s);return null==a?null:new hf(a,null)};f.S=function(){return rc(this)};
f.G=function(a,b){return Gc(this,b)};f.X=function(){return nc};f.ba=function(a,b){return fd(b,this)};f.ca=function(a,b,c){return gd(b,c,this)};f.ea=function(){return this.s.ea(null).F};f.ha=function(){var a=(null!=this.s?this.s.h&128||D===this.s.Wa||(this.s.h?0:F(kb,this.s)):F(kb,this.s))?this.s.W():T(this.s);return null!=a?new hf(a,null):nc};f.H=function(){return this};f.O=function(a,b){return b===this.pa?this:new hf(this.s,b)};f.U=function(a,b){return Hc(b,this)};hf.prototype[Wa]=function(){return qc(this)};
function xe(a){return(a=Q(a))?new hf(a,null):null}function Ce(a){return rb(a)}function sd(a){if(null!=a&&(a.o&4096||D===a.Ib))return a.name;if("string"===typeof a)return a;throw Error(["Doesn't support name: ",K.a(a)].join(""));}function jf(a){a:for(var b=a;;)if(b=Q(b))b=T(b);else break a;return a}
function kf(a,b,c,d,e,g,h){var k=Ka;Ka=null==Ka?null:Ka-1;try{if(null!=Ka&&0>Ka)return Jb(a,"#");Jb(a,c);if(0===Sa.a(g))Q(h)&&Jb(a,function(){var t=lf.a(g);return E(t)?t:"..."}());else{if(Q(h)){var l=S(h);b.g?b.g(l,a,g):b.call(null,l,a,g)}for(var m=T(h),q=Sa.a(g)-1;;)if(!m||null!=q&&0===q){Q(m)&&0===q&&(Jb(a,d),Jb(a,function(){var t=lf.a(g);return E(t)?t:"..."}()));break}else{Jb(a,d);var n=S(m);c=a;h=g;b.g?b.g(n,c,h):b.call(null,n,c,h);var r=T(m);c=q-1;m=r;q=c}}return Jb(a,e)}finally{Ka=k}}
function mf(a,b){b=Q(b);for(var c=null,d=0,e=0;;)if(e<d){var g=c.T(null,e);Jb(a,g);e+=1}else if(b=Q(b))c=b,ad(c)?(b=Rb(c),d=Sb(c),c=b,g=X(b),b=d,d=g):(g=S(c),Jb(a,g),b=T(c),c=null,d=0),e=0;else return null}function nf(a){if(null==Ga)throw Error("No *print-fn* fn set for evaluation environment");Ga.call(null,a)}var of={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function pf(a){return['"',K.a(a.replace(/[\\"\b\f\n\r\t]/g,function(b){return of[b]})),'"'].join("")}
function qf(a,b){return ed(jc.b(a,Qa))?null!=b&&(b.h&131072||D===b.Hb)?null!=Uc(b):!1:!1}
function rf(a,b,c){if(null==a)return Jb(b,"nil");if(qf(c,a)){Jb(b,"^");var d=Uc(a);sf.g?sf.g(d,b,c):sf.call(null,d,b,c);Jb(b," ")}if(a.ub)return a.Lb(b);if(null!=a?a.h&2147483648||D===a.aa||(a.h?0:F(Kb,a)):F(Kb,a))return Lb(a,b,c);if(!0===a||!1===a)return Jb(b,K.a(a));if("number"===typeof a)return Jb(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===Number.NEGATIVE_INFINITY?"##-Inf":K.a(a));if(null!=a&&a.constructor===Object)return Jb(b,"#js "),d=Rd.b(function(g){var h=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;
if("string"===typeof g)if(h=h.exec(g),oc.b(S(h),g))if(1===X(h))h=S(h);else if(E(te.a?te.a(h):te.call(null,h)))h=new Md(null,2,5,Nd,[Be.a?Be.a(h):Be.call(null,h),Ce.a?Ce.a(h):Ce.call(null,h)],null);else if($c(h))h=Tc(h,null);else if(Array.isArray(h))b:{var k=h.length;if(32>k)h=new Md(null,k,5,Nd,h,null);else for(var l=32,m=(new Md(null,32,5,Nd,h.slice(0,32),null)).Va(null);;)if(l<k){var q=l+1;m=Cd.b(m,h[l]);l=q}else{h=Ob(m);break b}}else h=Ob(Za(Nb,Mb(Kc),h));else h=null;else throw new TypeError("re-matches must match against a string.");
return new se(null!=h?rd.a(g):g,a[g])},za(a)),tf.V?tf.V(d,sf,b,c):tf.call(null,d,sf,b,c);if(Array.isArray(a))return kf(b,sf,"#js ["," ","]",c,a);if("string"==typeof a)return E(Pa.a(c))?Jb(b,pf(a)):Jb(b,a);if("function"==w(a)){var e=a.name;c=E(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Function":e;return mf(b,Ic(["#object[",c,E(!1)?[' "',K.a(a),'"'].join(""):"","]"]))}if(a instanceof Date)return c=function(g,h){for(g=K.a(g);;)if(g.length<h)g=["0",g].join("");else return g},mf(b,
Ic(['#inst "',K.a(a.getUTCFullYear()),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return mf(b,Ic(['#"',a.source,'"']));if(E(function(){var g=null==a?null:a.constructor;return null==g?null:g.gb}()))return mf(b,Ic(["#object[",a.constructor.gb.replace(/\//g,"."),"]"]));e=function(){var g=null==a?null:a.constructor;return null==g?null:g.name}();c=
E(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Object":e;return null==a.constructor?mf(b,Ic(["#object[",c,"]"])):mf(b,Ic(["#object[",c," ",K.a(a),"]"]))}function sf(a,b,c){var d=uf.a(c);return E(d)?(c=Pc.g(c,vf,rf),d.g?d.g(a,b,c):d.call(null,a,b,c)):rf(a,b,c)}
function wf(a,b){var c=new Ba;a:{var d=new Xb(c);sf(S(a),d,b);a=Q(T(a));for(var e=null,g=0,h=0;;)if(h<g){var k=e.T(null,h);Jb(d," ");sf(k,d,b);h+=1}else if(a=Q(a))e=a,ad(e)?(a=Rb(e),g=Sb(e),e=a,k=X(a),a=g,g=k):(k=S(e),Jb(d," "),sf(k,d,b),a=T(e),e=null,g=0),h=0;else break a}return c}function xf(a,b){var c;(c=null==a)||(c=Q(a),c=null==c?!0:!1===c?!0:!1);return c?"":K.a(wf(a,b))}function yf(a){var b=Pc.g(Ma(),Pa,!1);nf(xf(a,b));E(Ja)?(a=Ma(),nf("\n"),a=(jc.b(a,Oa),null)):a=null;return a}
function A(a){return a instanceof ic?v.b(null,sd(a)):rd.b(null,sd(a))}function C(a){if(E(!1)){var b=Q(a),c=Q(b),d=S(c);T(c);Oc(d,0,null);Oc(d,1,null);c=Mc(a);for(a=null;;){d=a;b=Q(b);a=S(b);var e=T(b),g=a;a=Oc(g,0,null);b=Oc(g,1,null);if(E(g))if(a instanceof qd||a instanceof ic)if(E(d))if(oc.b(d,x(a)))c=Pc.g(c,A(a),b),a=d,b=e;else return null;else if(d=x(a),E(d))c=Pc.g(c,A(a),b),a=d,b=e;else return null;else return null;else return new Md(null,2,5,Nd,[d,c],null)}}else return null}
function zf(a,b,c,d,e){return kf(d,function(g,h,k){var l=qb(g);c.g?c.g(l,h,k):c.call(null,l,h,k);Jb(h," ");g=rb(g);return c.g?c.g(g,h,k):c.call(null,g,h,k)},[K.a(a),"{"].join(""),", ","}",e,Q(b))}function tf(a,b,c,d){var e=Xc(a)?C(a):null,g=Oc(e,0,null);e=Oc(e,1,null);return E(g)?zf(["#:",K.a(g)].join(""),e,b,c,d):zf(null,a,b,c,d)}lc.prototype.aa=D;lc.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};td.prototype.aa=D;td.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};
se.prototype.aa=D;se.prototype.N=function(a,b,c){return kf(b,sf,"["," ","]",c,this)};Xe.prototype.aa=D;Xe.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};ue.prototype.aa=D;ue.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};ie.prototype.aa=D;ie.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};pd.prototype.aa=D;pd.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};bf.prototype.aa=D;bf.prototype.N=function(a,b,c){return tf(this,sf,b,c)};
Ze.prototype.aa=D;Ze.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};xd.prototype.aa=D;xd.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};hf.prototype.aa=D;hf.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};Md.prototype.aa=D;Md.prototype.N=function(a,b,c){return kf(b,sf,"["," ","]",c,this)};od.prototype.aa=D;od.prototype.N=function(a,b){return Jb(b,"()")};Na.prototype.aa=D;Na.prototype.N=function(a,b,c){return tf(this,sf,b,c)};gf.prototype.aa=D;
gf.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};Lc.prototype.aa=D;Lc.prototype.N=function(a,b,c){return kf(b,sf,"("," ",")",c,this)};function Af(){}var Bf=function Bf(a){if(null!=a&&null!=a.Cb)return a.Cb(a);var c=Bf[w(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Bf._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw I("IEncodeJS.-clj-\x3ejs",a);};
function G(a,b){return(null!=a?D===a.Bb||(a.tb?0:F(Af,a)):F(Af,a))?Bf(a):"string"===typeof a||"number"===typeof a||a instanceof qd||a instanceof ic?b.a?b.a(a):b.call(null,a):xf(Ic([a]),Ma())}var Cf=function Cf(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Cf.w(arguments[0],1<c.length?new lc(c.slice(1),0,null):null)};
Cf.w=function(a,b){b=null!=b&&(b.h&64||D===b.Na)?Jd(ef,b):b;var c=jc.g(b,Df,sd),d=function h(g){if(null==g)return null;if(null!=g?D===g.Bb||(g.tb?0:F(Af,g)):F(Af,g))return Bf(g);if(g instanceof qd)return c.a?c.a(g):c.call(null,g);if(g instanceof ic)return K.a(g);if(Xc(g)){var k={};g=Q(g);for(var l=null,m=0,q=0;;)if(q<m){var n=l.T(null,q),r=Oc(n,0,null);n=Oc(n,1,null);r=G(r,d);n=h(n);k[r]=n;q+=1}else if(g=Q(g))ad(g)?(m=Rb(g),g=Sb(g),l=m,m=X(m)):(m=S(g),l=Oc(m,0,null),m=Oc(m,1,null),l=G(l,d),m=h(m),
k[l]=m,g=T(g),l=null,m=0),q=0;else break;return k}if(Vc(g)){k=[];g=Q(Rd.b(h,g));l=null;for(q=m=0;;)if(q<m)r=l.T(null,q),k.push(r),q+=1;else if(g=Q(g))l=g,ad(l)?(g=Rb(l),q=Sb(l),l=g,m=X(g),g=q):(g=S(l),k.push(g),g=T(l),l=null,m=0),q=0;else break;return k}return g};return d(a)};Cf.P=1;Cf.I=function(a){var b=S(a);a=T(a);return this.w(b,a)};function Ef(){}
var Ff=function Ff(a,b){if(null!=a&&null!=a.Ab)return a.Ab(a,b);var d=Ff[w(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Ff._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw I("IEncodeClojure.-js-\x3eclj",a);};
function Gf(a){var b=Ic([Hf,!1]),c=null!=b&&(b.h&64||D===b.Na)?Jd(ef,b):b;c=jc.b(c,Hf);var d=E(c)?rd:K;return function h(g){return(null!=g?D===g.Rb||(g.tb?0:F(Ef,g)):F(Ef,g))?Ff(g,Jd(ff,b)):dd(g)?jf(Rd.b(h,g)):te(g)?new se(h(qb(g)),h(rb(g))):Vc(g)?Sd(Mc(g),Rd.a(h),g):Array.isArray(g)?Ob(Za(function(k,l){return Cd.b(k,h(l))},Mb(Kc),g)):(null==g?null:g.constructor)===Object?Ob(Za(function(k,l){var m=d.a?d.a(l):d.call(null,l);l=h(null!==g&&l in g?g[l]:void 0);return Pb(k,m,l)},Mb(Pd),za(g))):g}(a)}
"undefined"!==typeof console&&Ta();oc.b("nodejs","nodejs");Ta();var Sa=new qd(null,"print-length","print-length",1931866356),Oa=new qd(null,"flush-on-newline","flush-on-newline",-151457939),Qa=new qd(null,"meta","meta",1499536964),Hf=new qd(null,"keywordize-keys","keywordize-keys",1310784252),y=new ic(null,"meta6275","meta6275",-664781814,null),vf=new qd(null,"fallback-impl","fallback-impl",-1501286995),Pa=new qd(null,"readably","readably",1129599760),Df=new qd(null,"keyword-fn","keyword-fn",-64566675),uf=new qd(null,"alt-impl","alt-impl",670969595),Ra=new qd(null,
"dup","dup",556298533),lf=new qd(null,"more-marker","more-marker",-14717935);require("os");var Mf=require("vscode");var Lf=require("child_process");function Nf(a,b,c){Mf.window.showInformationMessage("invoking helper...");var d=Lf.spawn([K.a(Mf.extensions.getExtension("undefined_publisher.vscode-abridge").extensionPath),"/bin/abridge"].join(""),[],{}),e=d.stdout,g=d.stdin;e.on("data",function(h){h=jc.b(Gf(JSON.parse(h)),"result");h=Oc(h,0,null);return E(h)?(h=Cf(Rd.b(function(k){var l=Oc(k,0,null);k=Oc(k,1,null);return Mf.FoldingRange(l-1,k-1)},h)),a.a?a.a(h):a.call(null,h)):b.a?b.a(null):b.call(null,null)});e.on("end",function(){return yf(Ic(["finished!"]))});
d.on("close",function(h){return yf(Ic([["exit code: ",K.a(h)].join("")]))});d.on("error",function(h){yf(Ic([["err: ",K.a(h)].join("")]));return b.a?b.a(null):b.call(null,null)});return g.end(JSON.stringify(Cf(new Na(null,4,["jsonrpc","2.0","method","abridge-strings","params",new Md(null,1,5,Nd,[c],null),"id",1],null))))};shadow$umd$export={activate:function(a){console.log("activate called");var b=Mf.languages.registerFoldingRangeProvider({scheme:"file",language:"clojure"},{provideFoldingRanges:function(c){var d=c.getText();return new Promise(function(e,g){return Nf(e,g,d)})}});return a.subscriptions.push(b)},deactivate:function(){return null}};

  return shadow$umd$export;
});
